jooby-commons-email/src/main/java/org/jooby/internal/mail/EmailFactory.java
Apache Commons Email's setMsg() automatically wraps your markup in `<html><body><pre>`, which is not desirable.
=> HTML mail wrapped in extra markup

doc/index.html, resources/scripts/application.js, resources/styles/application.css, resources/styles/devices.css
Pages with sidebar (docs and guides) are now wider (max width changed from 1200px to 1400px)
=> make pages with sidebar wider

md/routes.md
`Route.Err` does not seems to exist. It seems that `Err` was meant.
=> Correct typo in  'Routes' documentation

coverage-report/src/test/java/org/jooby/issues/Issue273.java, coverage-report/src/test/java/org/jooby/issues/Issue273b.java, jooby/src/main/java/org/jooby/Request.java, jooby/src/main/java/org/jooby/internal/RequestImpl.java, jooby/src/test/java/org/jooby/RequestForwardingTest.java, jooby/src/test/java/org/jooby/RequestTest.java
Following the addition of:
- `List<Locale> locales(BiFunction<List<Locale.LanguageRange>, List<Locale>, List<Locale>> filter`
- `Locale locale(BiFunction<List<Locale.LanguageRange>, List<Locale>, Locale> filter)`
`Locale locale(Iterable<Locale> locales)` and `Locale locale(Locale... locales)`
were made redundant by the new two functions. This use case can be implemented
in the following way:
List<Locale> supportedLocales = ...
Locale locale = req.locale((ranges, locales) ->
Locale.lookup(ranges, supportedLocales));
`List<Locale> locales()` is just an shorthand for `locales(Locale::filter)`.
`Locale locale()` simply returns the first element of `locales` or the default
locale as per `app.lang` if there are no matches. This function is expected to
be the most used one.
Issue #273
=> Refactor the Request locale API

jooby-hotreload/src/main/java/org/jooby/hotreload/AppModule.java, jooby-hotreload/src/main/java/org/jooby/hotreload/Watcher.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S2275 - Printf-style format strings should not lead to unexpected behavior at runtime.
squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
squid:S1155 - Collection.isEmpty() should be used to test for emptiness.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S2275
https://dev.eclipse.org/sonar/rules/show/squid:S1213
https://dev.eclipse.org/sonar/rules/show/squid:S1155
Please let me know if you have any questions.
George Kankava
=> Multiple code improvements - squid:S2275, squid:S1213, squid:S1155

jooby-jetty/src/main/java/org/jooby/internal/jetty/JettyHandler.java, jooby-jetty/src/main/java/org/jooby/internal/jetty/JettyServer.java, jooby-jetty/src/main/java/org/jooby/internal/jetty/JettyWebSocket.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1192 - String literals should not be duplicated.
squid:S1066 - Collapsible "if" statements should be merged. 
squid:S1193 - Exception types should not be tested using "instanceof" in catch blocks.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1192
https://dev.eclipse.org/sonar/rules/show/squid:S1066
https://dev.eclipse.org/sonar/rules/show/squid:S1193
Please let me know if you have any questions.
George Kankava
=> Multiple code improvements - squid:S1192, squid:S1066, squid:S1193

coverage-report/src/test/java/org/jooby/hbm/data/Car.java, coverage-report/src/test/java/org/jooby/session/SessionConfigCookieFeature.java, coverage-report/src/test/java/org/jooby/session/SessionCookieFeature.java, coverage-report/src/test/java/org/jooby/session/SessionCookieNoSecretFeature.java, coverage-report/src/test/java/org/jooby/session/SessionWithMaxAgeShouldAlwaysSendHeaderFeature.java
Hardcoded bean validation messages to US locale ones to make test pass independent of host system locale.
=> Fix #309 Jooby coverage-report BeanvalidationFeature fails with German locale

jooby-jdbc/src/main/java/org/jooby/jdbc/Jdbc.java, jooby-querydsl/pom.xml, jooby-querydsl/src/main/java/org/jooby/querydsl/QueryDSL.java, jooby-querydsl/src/main/java/org/jooby/querydsl/SQLDialectDetector.java, jooby-querydsl/src/main/java/org/jooby/querydsl/internal/ConfigurationProvider.java, jooby-querydsl/src/main/java/org/jooby/querydsl/internal/SQLQueryFactoryProvider.java, jooby-querydsl/src/main/java/org/jooby/querydsl/internal/SQLTemplatesProvider.java, jooby-querydsl/src/test/java/org/jooby/querydsl/QueryDSLTest.java, jooby-querydsl/src/test/java/org/jooby/querydsl/SQLDialectDetectorTest.java, jooby-querydsl/src/test/java/org/jooby/querydsl/internal/ConfigurationProviderTest.java, jooby-querydsl/src/test/java/org/jooby/querydsl/internal/SQLQueryFactoryProviderTest.java, jooby-querydsl/src/test/java/org/jooby/querydsl/internal/SQLTemplatesProviderTest.java, pom.xml
I kinda hope this isn't unsolicited as I've seen, you guys seem to be working on a QueryDSL module of your own, using QueryDSL with JPA. I've recently implemented a small service based on Jooby and tried out QueryDSL on plain JDBC specifically because I had relatively few interactions with the DB and wanted to avoid the bload of JPA.
...and suddenly I ended up with everything to exract a generic Jooby module for integrating QueryDSL over JDBC.
I've borrowed heavily from the jOOQ module to get the layout in shape. Biggest hurdle was the actual lack of any SQL Dialect detection, but turns out, nobody seems to do anything smarter than examining the DB URL string.
Maybe you've already got this on the backburner or decide it is redundant to have, but I'd like to hear your input on this!
=> Jooby QueryDSL-JDBC support

jooby-assets/src/test/java/org/jooby/assets/AssetCompilerTest.java
I had another Whoopsie with a test for number formatting on German locale. I wrote a little wrapper function that'll set the default locale for a block of test code and will reset the original default locale afterwards.
Split the test itself between a US and a GERMAN locale section.
=> Add Locale Wrapper to AssetCompilerTest

jooby/src/main/java/org/jooby/internal/RoutePattern.java, jooby/src/test/java/org/jooby/internal/RoutePatternTest.java, md/routes.md
Enhances the routing path matcher by allowing the binding of globs as a named parameter using the following syntax:
```java
get("/foo/**:tail", req -> {
doSomething(req.params("tail")); // GET/foo/bar/baz -> tail == "bar/baz"
});
get("/foo/{tail:**}", req -> {
doSomething(eq.params("tail")); // same
});
get("/foo/**:inbetween/end", req -> {
doSomething(eq.params("inbetween")); // GET/foo/bar/baz/end -> inbetween == "bar/baz"
});
get("/foo/{inbetween:**}/end", req -> {
doSomething(eq.params("inbetween")); // same
});
```
=> Add named globbing using "**:name" or "{name:**}"

coverage-report/pom.xml, jooby-caffeine/pom.xml, jooby-caffeine/src/main/java/org/jooby/caffeine/CaffeineCache.java, jooby-caffeine/src/main/java/org/jooby/caffeine/CaffeineSessionStore.java, jooby-caffeine/src/test/java/org/jooby/caffeine/CaffeineCacheTest.java, jooby-caffeine/src/test/java/org/jooby/caffeine/CaffeineSessionStoreTest.java, md/doc/caffeine/caffeine.md, pom.xml
This is derived from the Guava module. The changes were,
* Replace Guava types with Caffeine's (`Cache`, `LoadingCache`, `CaffeineSpec`)
* Add AsyncLoadingCache support
* Update documentation, modules, etc.
Note that `AsyncLoadingCache` does not extend the Cache interface due to some minor differences. It would ideally be a `LoadingCache<K, CompletableFuture<V>>`, but that would require allowing a null return value (as Caffeine does not throw an exception on a cache miss). To support this type, `doWithAsync` was added along with `AsyncCallback`. The private `callback` instance has weaker type safety, but is internal so this has no negative effect. That approach allowed for making the most minimal changes from the original Guava code.
=> add Caffeine cache support

pom.xml
Note: This also requires a newer Apache HTTP client (4.5.2). See https://aws.amazon.com/releasenotes/9979983567247718
=> Upgrade to latest stable AWS Java SDK

jooby-jdbc/src/main/java/org/jooby/jdbc/Jdbc.java, jooby-jdbc/src/test/java/org/jooby/jdbc/JdbcTest.java
Execute callback just before HikariDataSource creation, passing HikariConfig and Config objects
=> jooby-jdbc configure callback fix

jooby-mongodb/pom.xml, jooby-mongodb/src/main/java/org/jooby/mongodb/MongoSessionStore.java, jooby-mongodb/src/test/java/apps/MongodbApp.java, jooby-mongodb/src/test/java/org/jooby/mongodb/MongodbSessionStoreTest.java
* upgrade mongo API on MongoSessionStore
=> mongodb session store doesn't work fix #590

jooby-executor/src/main/java/org/jooby/exec/Exec.java, jooby-executor/src/test/java/org/jooby/exec/ExecTest.java
Rational: It would be a good idea to have an alternative configuration style for custom executors like:
executors {
custom {
type = fixed
size = ${runtime.processors-x2}
}
}
=> Executors pool size config

jooby-jetty/src/main/java/org/jooby/internal/jetty/JettyServer.java, jooby-jetty/src/test/java/org/jooby/internal/jetty/JettyServerTest.java, jooby-netty/src/main/java/org/jooby/internal/netty/NettyServer.java, jooby-netty/src/test/java/org/jooby/internal/netty/NettyServerTest.java, jooby-servlet/src/main/java/org/jooby/servlet/ServletContainer.java, jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowServer.java, jooby-undertow/src/test/java/org/jooby/internal/undertow/UndertowServerTest.java, jooby/src/main/java/org/jooby/Jooby.java, jooby/src/main/java/org/jooby/internal/ServerExecutorProvider.java, jooby/src/main/java/org/jooby/spi/Server.java, jooby/src/test/java/org/jooby/issues/Issue430.java
Rational: When doing async tasks with RxJava or other frameworks, it would be a good idea to reuse the server's worker threads.
=> Server worker executor

coverage-report/pom.xml, jooby-filewatcher/.gitignore, jooby-filewatcher/pom.xml, jooby-filewatcher/src/main/java/org/jooby/filewatcher/FileEventHandler.java, jooby-filewatcher/src/main/java/org/jooby/filewatcher/FileEventOptions.java, jooby-filewatcher/src/main/java/org/jooby/filewatcher/FileMonitor.java, jooby-filewatcher/src/main/java/org/jooby/filewatcher/FileWatcher.java, jooby-filewatcher/src/main/java/org/jooby/filewatcher/FirstOfPathMatcher.java, jooby-filewatcher/src/main/java/org/jooby/filewatcher/GlobPathMatcher.java, jooby-filewatcher/src/main/java/org/jooby/filewatcher/WatchEventKind.java, jooby-filewatcher/src/main/java/org/jooby/filewatcher/WatchEventModifier.java, jooby-filewatcher/src/test/java/filewatcher/FileWatcherApp.java, jooby-filewatcher/src/test/java/filewatcher/MyFileEventHandler.java, jooby-filewatcher/src/test/java/org/jooby/filewatcher/FileEventOptionsTest.java, jooby-filewatcher/src/test/java/org/jooby/filewatcher/FileMonitorTest.java, jooby-filewatcher/src/test/java/org/jooby/filewatcher/FileWatcherTest.java, jooby-filewatcher/src/test/java/org/jooby/filewatcher/FirstOfPathMatcherTest.java, jooby-filewatcher/src/test/java/org/jooby/filewatcher/WatchEventKindTest.java, jooby-filewatcher/src/test/java/org/jooby/filewatcher/WatchEventModifierTest.java, jooby/pom.xml, md/doc/filewatcher/filewatcher.md, md/guides/guide.footer.md, md/guides/jdbi.md, pom.xml
Watches for file system changes or event. It uses a watch service to monitor a directory for changes so that it can update its display of the list of files when files are created or deleted.
```xml
<dependency>
<groupId>org.jooby</groupId>
<artifactId>jooby-file watcher</artifactId>
<version>{{version}}</version>
</dependency>
```
Watch ```mydir``` and listen for create, modify or delete event on all files under it:
```java
{
use(new FileWatcher()
.register(Paths.get("mydir"), (kind, path) -> {
log.info("found {} on {}", kind, path);
});
);
}
```
You can specify a {@link FileEventHandler} instance or class while registering a path:
Instance:
```java
{
use(new FileWatcher()
.register(Paths.get("mydir"), (kind, path) -> {
log.info("found {} on {}", kind, path);
});
);
}
```
Class reference: …
=> File watcher module

jooby-mongodb/src/main/java/org/jooby/mongodb/MongoSessionStore.java, jooby-mongodb/src/test/java/org/jooby/mongodb/MongodbSessionStoreTest.java
=> OAuth error using MongoSessionStore fix #654

coverage-report/src/test/java/org/jooby/issues/Issue548.java, coverage-report/src/test/java/org/jooby/issues/Issue548b.java, coverage-report/src/test/java/org/jooby/issues/Issue548c.java, coverage-report/src/test/java/org/jooby/issues/Issue548d.java, jooby-crash/src/main/java/org/jooby/crash/WebShellHandler.java, jooby-jetty/src/main/java/org/jooby/internal/jetty/JettyWebSocket.java, jooby-jetty/src/test/java/org/jooby/internal/jetty/JettyWebSocketTest.java, jooby-netty/src/main/java/org/jooby/internal/netty/NettyWebSocket.java, jooby-netty/src/test/java/org/jooby/internal/netty/NettyWebSocketTest.java, jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowWebSocket.java, jooby-undertow/src/test/java/org/jooby/internal/undertow/UndertowWebSocketTest.java, jooby/src/main/java/org/jooby/Jooby.java, jooby/src/main/java/org/jooby/Router.java, jooby/src/main/java/org/jooby/WebSocket.java, jooby/src/main/java/org/jooby/internal/WebSocketImpl.java, jooby/src/main/java/org/jooby/internal/WebSocketRendererContext.java, jooby/src/main/java/org/jooby/internal/mvc/MvcWebSocket.java, jooby/src/main/java/org/jooby/spi/NativeWebSocket.java, jooby/src/test/java/org/jooby/WebSocketTest.java, jooby/src/test/java/org/jooby/internal/WebSocketImplTest.java, jooby/src/test/java/org/jooby/internal/WebSocketRendererContextTest.java, jooby/src/test/java/org/jooby/internal/mvc/MvcWebSocketTest.java, md/.web-sockets.md.html, md/web-sockets.md
* rename web socket callbacks
* implement class/mvc listener using new callbacks
```java
@Path("/ws")
@Consumes("json")
@Produces("json")
class MyHandler implements WebSocket.OnMessage<MyObject> {
public void onMessage(MyObject object) {
ws.send(new MyResponseObject());
}
}
```
/cc @jschneider
=> MVC should support WebSockets fix #548

jooby-filewatcher/src/main/java/org/jooby/filewatcher/FileMonitor.java, jooby-filewatcher/src/main/java/org/jooby/filewatcher/FileWatcher.java, jooby-livereload/pom.xml, jooby-livereload/src/main/java/org/jooby/livereload/LiveReload.java, jooby-livereload/src/main/resources/org/jooby/livereload/livereload.js, jooby-run/src/main/java/org/jooby/run/Main.java, md/doc/livereload/livereload.md, pom.xml
<a href="http://livereload.com">LiveReload</a> monitors changes in the file system. As soon as you save a file, it is preprocessed as needed, and the browser is refreshed.
Even cooler, when you change a CSS file or an image, the browser is updated instantly without reloading the page.
* livereload.js route
* livereload websocket
```xml
<dependency>
<groupId>org.jooby</groupId>
<artifactId>jooby-livereload</artifactId>
<version>{{version}}</version>
</dependency>
```
```java
{
use(new Jackson());
use(new LiveReload());
}
```
This module is available as long you run in development: `application.env=dev`.
Install the <a href="http://livereload.com/extensions/">LiveReload browser extension.</a>
Add the ```livereload.js``` to your web page.
You can do this manually:
```
<script …
```
=> LiveReload module fix #670

jooby-servlet/src/main/java/org/jooby/servlet/ServletServletRequest.java, jooby-servlet/src/test/java/org/jooby/servlet/ServletServletRequestTest.java, jooby/src/main/java/org/jooby/internal/HttpHandlerImpl.java, jooby/src/main/java/org/jooby/spi/NativeRequest.java
Fix for #674
I couldn't really find a good place to write a test to the `HttpHandlerImpl` change, but since it's a small, simple change, maybe we're good without a test.
Anyway, if you think it's worth it I can write the test, I'd just need a pointer to specific test case I could use.
=> Exposes Servlet Request attributes

jooby-maven-plugin/src/main/java/org/jooby/JoobyMojo.java, jooby-run/src/main/java/org/jooby/run/Main.java
=> logback.dev.xml not being read fix #665

pom.xml
Was having problems with ebean code enhancement because of this bug:
https://issues.apache.org/jira/browse/MCOMPILER-236
After update everything seems to be working fine.
=> bump maven-compliler plugin version because of bug MCOMPILER-236

coverage-report/pom.xml, jooby-consul/pom.xml, jooby-consul/src/main/java/org/jooby/consul/Consulby.java, jooby-consul/src/main/resources/org/jooby/consul/consul.conf, jooby-consul/src/test/java/org/jooby/consul/ConsulbyTest.java, md/doc/consul/consul.md, pom.xml
A very little something I plan to use in my application.
It is a module that expose a client to communicate with [Consul](https://www.consul.io/), using the nice [OrbitzWorldwide/consul-client](https://github.com/OrbitzWorldwide/consul-client) lib.
I made the extra mile to make it generic (but not too much) enough to be reusable.
It is pretty straight forward (zero config) to use as a simple service registration with health check and service discovery module (this is what I intend to use it for).
You can see the [doc I started here](https://github.com/pierredavidbelanger/jooby/blob/jooby-consul/jooby-consul/README.md).
I will let you have a look at it.
If you like it, I will clean it up a little, add some tests and give it to you.
Do not hesitate to make me change everything, I am not …
=> initial commit for a jooby consul module

jooby-raml/src/main/java/org/jooby/internal/raml/RamlType.java
Jooby RamlType ignore properties starting with `_`, for example `_ebeanServer`.
This resolves the issue #718
=> jooby raml ignore class hidden properties

jooby-ftl/src/main/java/org/jooby/internal/ftl/Engine.java, jooby-hbs/src/main/java/org/jooby/internal/hbs/HbsEngine.java, jooby-jade/src/main/java/org/jooby/jade/Engine.java, jooby-pebble/src/main/java/org/jooby/pebble/PebbleRenderer.java, jooby-pebble/src/test/java/org/jooby/pebble/Issue725.java, jooby-pebble/src/test/java/org/jooby/pebble/PebbleRendererTest.java, jooby-thymeleaf/src/main/java/org/jooby/thymeleaf/ThlEngine.java
=> I18N support in jooby. fix #755

modules/jooby-maven-plugin/src/main/java/org/jooby/RouteProcessorMojo.java
I was having issues with my build cycle and the main reason was because `jooby:spec` forks the compilation to generate the spec file and after this the default compilation occurs.
`jooby:spec` executes the build to the `process-classes` phase.
Besides my compilation problems (mainly because of ebean and querybean enhacement), another down side of this is that the compilation is much slower (2 compilations).
This PR just removes the execution of the `process-classes` and if the plugin is set to execute in the phase `process-classes` everything works as expected.
=> remove force recompilation of classes from jooby:spec

jooby/src/test/java/org/jooby/RequestLoggerTest.java
When running the test suite on my french system, it fails because of the expectations on the date format.
=> Fix RequestLoggerTest on a non english system

doc/doc/gradle/gradle.md
Found related native transport libraries for any issues related to it not existing. 
[Netty documentation](http://netty.io/wiki/native-transports.html)
=> added dependency for native epoll

jooby/src/main/java/org/jooby/Request.java, modules/coverage-report/src/test/java/org/jooby/issues/Issue273.java, modules/coverage-report/src/test/java/org/jooby/issues/Issue877.java
Uses `Locale#lookup` instead of `Locale#filter` + findFirst and fallback. As a result, it will return the locale with the closest match in case that is possible.
Example: with a language setting of "en, de", a request with the `Accept-Language` header set to `de-CH` will now return `de` instead of `en`.
Closes #877
=> Change default behavior of Request.locale()

doc/doc/maven-plugin/maven.md, doc/gradle-jooby-run.md, modules/jooby-gradle-plugin/src/main/java/org/jooby/run/JoobyPlugin.java, modules/jooby-gradle-plugin/src/main/java/org/jooby/run/JoobyTask.java, modules/jooby-maven-plugin/src/main/java/org/jooby/JoobyMojo.java
This will allow people to configure the src extensions that trigger rebuild so that they can add Kotlin or Rocker file extensions to trigger re-compilation.
=> Making the src extensions that trigger rebuild configurable

modules/jooby-netty/src/main/java/org/jooby/internal/netty/NettySslContext.java, modules/jooby-netty/src/test/java/org/jooby/internal/netty/NettySslContextTest.java
- NettySslContext now explicitly requests client auth when `ssl.trust.cert` is used.
- NettySslContextTest now checks for this setting.
=> Enable client certificate authentication. Fix #904.

jooby/src/main/java/org/jooby/Jooby.java, jooby/src/main/java/org/jooby/Router.java, jooby/src/test/java/org/jooby/JoobyTest.java
Now you can specify the `path` when using an MVC route.
Example:
```java
use("/pets", MyMVCRoute.class);
```
=> Support path when using MVC class

doc/doc/assets-sass/sass.md, modules/jooby-assets-sass/README.md
The Sass README.md file provides an example with camelcased `sourceMap` property, while the code and tests expect an all lowercase `sourcemap`. This leads to the configuration not being picked up when you follow the example. See [this test](https://github.com/yholkamp/jooby/blob/8ae900fe3a3b724e40becec7bd1671785faa01ff/modules/jooby-assets-sass/src/test/java/org/jooby/assets/JSassTest.java#L170) and [this code](https://github.com/yholkamp/jooby/blob/19889ea7c0a2af0764d4c3aab2ca86bf98cbe8a7/modules/jooby-assets-sass/src/main/java/org/jooby/assets/Sass.java#L398) for reference.
=> Sass README has an invalid configuration example

modules/jooby-assets-sass/src/main/java/org/jooby/assets/Sass.java, modules/jooby-assets-sass/src/test/java/org/jooby/assets/JSassTest.java, modules/jooby-assets-sass/src/test/resources/relative/nested/bar.scss, modules/jooby-assets/src/main/java/org/jooby/assets/AssetCompiler.java, modules/jooby-assets/src/main/java/org/jooby/assets/AssetProcessor.java
This pull request aims to resolve issue #968, with a cleaner solution than suggested in pull request #974 . To provide access to the `ClassLoader` instance, I've added a new `process` method to the `AssetProcessor` that takes an additional parameter (the class loader instance) and calls the existing `process` method for backwards compatibility. I've then updated the `Sass` class to overwrite the new process method.
The Sass class had unused `FS` and `CP` constants that I've adapted to include the provided ClassLoader, removing the FileResolver enum as it's become redundant.
=> Assets-sass module file resolver patching

modules/jooby-maven-plugin/src/main/java/org/jooby/JoobyMojo.java
When `jooby:run` was reloading a project with ebean, entity classes where not being enhanced.
=> fix ebean: add query-beans maven integration

modules/jooby-frontend/src/main/java/org/jooby/frontend/Yarn.java
eirslett/frontend-maven-plugin provides separate classes for Yarn to be used instead of their Npm version.
=> Fix Yarn downloader using proper classes #1037

doc/req.md, jooby/src/main/java/org/jooby/internal/mvc/RequestParam.java, jooby/src/test/java/org/jooby/internal/mvc/RequestParamTest.java
While debugging my application I ran in to some `@Local` behavior that I didn't immediately expect, in that matching happens based on the parameter name rather than type (like with injection). In hindsight this makes perfect sense and I figured I'd add a note about this in the documentation to help others who run in to this.
Additionally I noticed that currently the error you receive when you define an mvc route with has a non-optional `@Local` field, i.e. `@Local String myLocal` and this value is not present, you receive the following exception/trace, which provides little debug information:
```
java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:135)
at org.jooby.internal.mvc.RequestParam.lambda$static$16(RequestParam.java:319)
at …
```
=> Clarifying the @Local injection documentation & injection error

modules/jooby-jdbi3/pom.xml, pom.xml
Per [the Jdbi changelog](https://github.com/jdbi/jdbi/blob/ff1ee02/RELEASE_NOTES#L54-L55), Jdbi has moved to using `jdbi3-core` rather than `jdbi3` as artifact name after 3.0.0-beta2, which is the version currently in use in Jooby. 
Since there are quite a number of bugfixes that were added after this beta, in particular relating to Kotlin and nested bean mapping, I'd like to propose that we upgrade the Jdbi3 version to the latest, which is 3.0.1 on [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.jdbi%22%20).
=> Updating the Jdbi3 dependency version

modules/jooby-assets/src/main/java/org/jooby/assets/AssetClassLoader.java, modules/jooby-assets/src/main/java/org/jooby/assets/AssetCompiler.java, modules/jooby-assets/src/main/java/org/jooby/assets/Assets.java, modules/jooby-assets/src/test/java/org/jooby/assets/AssetClassLoaderTest.java, modules/jooby-maven-plugin/src/main/java/org/jooby/AssetMojo.java
Currently if you run the `AssetMojo` from another directory than the project root, asset compilation fails. Examples where this would happen are using Jooby in a Maven module of a larger project, in that case running `mvn package` on the main project would break as `package` is invoked on the Jooby submodule from the parent directory. Another example would be perhaps on a CI server compiling the app without changing directories via `mvn -f projectdir/pom.xml package`.
I'm aware that this isn't the recommended way to run Jooby but it'd be convenient to support this nonetheless as it makes it easier to integrate Jooby in to existing projects.
Since the `AssetMojo` has access to `mavenProject.basedir` which returns the proper base directory irrespective of the working directory, I've made …
=> Updating AssetMojo to honor the Maven project.baseDir

jooby/src/main/java/org/jooby/Jooby.java, jooby/src/test/java/org/jooby/JoobyTest.java, modules/coverage-report/src/test/java/org/jooby/ModuleProvidesFeature.java
When using dependency injection for modules that rely heavily on providers, Guice's `@Provides` support (https://github.com/google/guice/wiki/ProvidesMethods) can be used to reduce the boilerplate that's otherwise required when registering `Provider` classes. Currently these annotations are not supported by Jooby.
With this pull request I'm proposing to add a method call in the Jooby `install` method that binds these annotated methods by using existing Guice functionality to generate a module for this. If a module has no such methods, the call will essentially be a no-op.
I'm curious to hear what you think about this proposal @jknack and thanks in advance for considering it.
=> Adding support for modules with @Provides annotated methods

modules/coverage-report/src/test/java/org/jooby/issues/Issue1194.java, modules/jooby-netty/src/main/java/org/jooby/internal/netty/NettyResponse.java, modules/jooby-netty/src/test/java/org/jooby/internal/netty/NettyResponseTest.java
Fixes #1194
Seems like in that case, there was no context flush occurring, thus the response stayed in the context's buffer indefinitely.
At least I hope I parsed that right as this was my first experience debugging Netty-related code.
=> Fix missing flush on Netty context

modules/jooby-assets-autoprefixer/README.md, modules/jooby-assets-babel/README.md, modules/jooby-assets-clean-css/README.md, modules/jooby-assets-closure-compiler/README.md, modules/jooby-assets-csslint/README.md, modules/jooby-assets-jscs/README.md, modules/jooby-assets-jshint/README.md, modules/jooby-assets-less/README.md, modules/jooby-assets-less4j/README.md, modules/jooby-assets-ng-annotate/README.md, modules/jooby-assets-requirejs/README.md, modules/jooby-assets-rollup/README.md, modules/jooby-assets-sass/README.md, modules/jooby-assets-svg-sprites/README.md, modules/jooby-assets-svg-symbol/README.md, modules/jooby-assets-uglify/README.md, modules/jooby-assets-yui-compressor/README.md, modules/jooby-commons-email/README.md, modules/jooby-gradle-plugin/README.md, modules/jooby-guava-cache/README.md, modules/jooby-lang-kotlin/README.md, modules/jooby-maven-plugin/README.md, modules/jooby-mongodb-rx/README.md, modules/jooby-rxjava-jdbc/README.md
A backslash needs to be escaped by a backslash in status.
see https://shields.io/#your-badge
=> Fix broken module name badges

doc/quickstart.md
If you execute archetype:generate in a non-empty folder, if may fail with this exception:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project XYZ: org.apache.maven.archetype.exception.InvalidPackaging: Unable to add module to the current project as it is not of packaging type 'pom'.
Therefore I added the text "make sure you are in an empty folder,..." to the quickstart.md.
=> added info about empty folder

modules/jooby-dist/src/main/resources/assemblies/jooby.stork.xml
A pull request fixing #1241. 
This only fixes the problem for Windows executables, I have not tested whether Linux/macOS executables are also affected.
=> Prevented filtering of stork executables

docs/execution-model.adoc, docs/index.adoc
Since jooby requests can be executed using
coroutines as well as threads, it is a better name.
Fixed some minor language issues.
=> Rename thread model to execution model in docs

modules/jooby-hbm/pom.xml, modules/jooby-hbm/src/main/java/org/jooby/hbm/Hbm.java, modules/jooby-hbm/src/test/java/org/jooby/hbm/HbmTest.java, pom.xml
This pull request upgrades `jooby-hbm` to use the latest stable version of Hibernate in the 5.3 series.
Beside simply bumping the version number, two additional changes were necessary:
- they marked the CDI-API is provided dependency, therefore `jooby-hbm` needs to depend on it explicitly: https://hibernate.atlassian.net/browse/HHH-11370
- the usage of `JpaIntegrator` is not necessary anymore, so it can be removed from the initialization code and tests: https://hibernate.atlassian.net/browse/HHH-11264
=> Upgrade to Hibernate 5.3.9

jooby/src/main/java/org/jooby/Request.java, jooby/src/main/java/org/jooby/internal/RequestImpl.java, jooby/src/main/java/org/jooby/spi/NativeRequest.java, jooby/src/test/java/org/jooby/RequestTest.java, modules/jooby-netty/src/main/java/org/jooby/internal/netty/NettyRequest.java, modules/jooby-servlet/src/main/java/org/jooby/servlet/ServletServletRequest.java, modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowRequest.java
Had a bit of an issue with getting bad request errors due to missing parameters on a Multipart form upload where the file size exceeded `server.http.MaxRequestSize`
Ideally would like to return a `400 Bad Request` but currently returns a `500 Error`, but the application log shows a more descriptive error, i.e. file size limit  instead of missing parameter.
If you could take a look at this and let me know how it can be improved I'd be happy to do that.
Thanks.
=> Refactored request handler to throw a better exception

modules/jooby-bom/pom.xml, pom.xml
mvn install fails on latest jdk1.8 with dokka-maven-plugin unable to find jdk tools.jar.
this is fixed in newer doka-maven-plugin version. check this out:
https://github.com/Kotlin/dokka/issues/272
https://github.com/Kotlin/dokka/issues/303
=> Fix build issue with JDK9 due to outdated dokka-maven-plugin

modules/jooby-crash/pom.xml, pom.xml
master `mvn install` fails to build due to missing classes in jooby-crash module. seems that some of the dependencies should be more explicit.
```
modules/jooby-crash/src/main/java/org/jooby/crash/WebShellHandler.java:[207,25] package org.crsh.cli.impl does not exist
```
full log:
https://gist.github.com/altmind/e8429c3e9cbfb1df86e58c52ef5572e9
=> Added explicit dependency on crsh-cli to fix maven compilation problem

docs/src/main/java/io/jooby/adoc/DependencyProcessor.java
The getting started section for gradle mentions to add
`compile: 'io.jooby:jooby-netty:2.0.0.M3'`
but the correct syntax is
`compile 'io.jooby:jooby-netty:2.0.0.M3'`
Don't know but DependencyProcessor seems like the only place mentioning `compile:`
=> gradle syntax is without colon for compile

modules/jooby-guice/src/main/java/io/jooby/di/Guiceby.java, modules/jooby-guice/src/main/java/io/jooby/di/ResourceModule.java
Relatively minor changes to the Guice module that binds the available resources on the injector instance, allowing for injection of for instance `DataSource` instances installed by the Hikari module.
=> 2.x Resource injection support

modules/jooby-apitool/src/main/java/org/jooby/internal/apitool/TypeJsonDeserializer.java, modules/jooby-apitool/src/test/java/org/jooby/internal/apitool/WildcardTypesTest.java
fixes https://github.com/jooby-project/jooby/issues/1317
and also covers parsing Lower Bounded Wildcard and Unbounded Wildcard types
=> apitool parser support response with wildcard types

modules/coverage-report/src/test/java/org/jooby/elasticsearch/ElasticsearchClientAPIFeature.java, modules/jooby-bom/pom.xml, modules/jooby-elasticsearch/pom.xml, modules/jooby-elasticsearch/src/main/java/org/jooby/elasticsearch/Elasticsearch.java, modules/jooby-elasticsearch/src/test/java/org/jooby/elasticsearch/ElasticsearchTest.java, pom.xml
This allows to use the fully fledged high level REST client from
Elasticsearch. This also keeps the low level rest client available, so
that it can be accessed as well in jooby apps.
=> Upgrade to Elasticsearch 7.2.0 REST client

modules/jooby-flyway/src/main/java/io/jooby/flyway/FlywayModule.java
The Flyway module was trying to remove a non-existent property for the `flyway.run` setting, which was causing things to fail on startup with `org.flywaydb.core.api.FlywayException: Unknown configuration property: flyway.run`.
The properties come through to that point with the `flyway.` prefix, so I corrected the property name to include it.
=> Fixed missing Flyway property name prefix

docs/asciidoc/dev-tools.adoc
The 2.0.2 documentation for the jooby-maven-plugin specifies a configuration tag
```
<sourceExtensions>java,kt</sourceExtension>
```
which is incorrect and is now called
```
<compileExtensions>
```
=> Update jooby-maven-plugin configuration

jooby/src/main/java/io/jooby/Value.java
The method Value.valueOrNull() is marked as NonNull, this fixes that and marks it as Nullable
Closes #1362
=> Make valueOrNull nullable

jooby/src/main/java/org/jooby/Err.java, jooby/src/main/java/org/jooby/internal/HttpHandlerImpl.java, jooby/src/main/java/org/jooby/internal/RouteImpl.java, jooby/src/test/java/org/jooby/DefaultErrHandlerTest.java
@jknack  Please review, especially the test case. I'm not familiar with it, i'm not sure if this line is correct:
`expect(env.xss("html")).andReturn(HtmlEscapers.htmlEscaper()::escape);`
=> Avoiding possible XSS attack through the default error handler

docs/asciidoc/routing.adoc, jooby/src/main/java/io/jooby/Route.java, jooby/src/main/java/io/jooby/internal/RouterImpl.java, jooby/src/main/java/io/jooby/internal/mvc/JaxrsAnnotationParser.java, jooby/src/main/java/io/jooby/internal/mvc/JoobyAnnotationParser.java, jooby/src/main/java/io/jooby/internal/mvc/MvcAnnotation.java, jooby/src/main/java/io/jooby/internal/mvc/MvcAnnotationParserBase.java, tests/src/test/java/examples/MvcAttributes.java, tests/src/test/java/examples/Role.java, tests/src/test/java/io/jooby/RouteAttributeTest.java
Hello, 
Follow from #1373 
So I have reworked my code to provide the same API for MVC and Script API.  
I also change my terminology to use the same one as in Jooby 1.x.
```
{
get("/foo", ctx -> "Foo")
.attribute("foo", "bar");
decorator(next -> ctx -> {
User user = ...;
String role = ctx.getRoute().attribute("Role"); 
if (user.hasRole(role)) {
return next.apply(ctx);
}      
throw new StatusCodeException(StatusCode.FORBIDDEN);                              
});
}
```
I have updated the Router documentation to reflect the changes.
And I have added some tests / examples.
=> Provide Route attributes for MVC and Script API.

docs/asciidoc/static-files.adoc
Updated the Java static file-system route example to match the correct Kotlin example. Java example used `Paths.get("static")` instead of the correct `Paths.get("www")` as in the Kotlin code example.
From:
```
.File system resources:
[source, java, role="primary"]
----
{
assets("/static/*", Paths.get("static")); <1>
}
----
.Kotlin
[source, kotlin, role="secondary"]
----
{
assets("/static/*", Paths.get("www"))  <1>
}
----
```
To:
```
.File system resources:
[source, java, role="primary"]
----
{
assets("/static/*", Paths.get("www")); <1>
}
----
.Kotlin
[source, kotlin, role="secondary"]
----
{
assets("/static/*", Paths.get("www"))  <1>
}
----
```
=> fix java example for static file-system example

jooby/src/main/java/io/jooby/Usage.java
Changed http link from `io.jooby` to `jooby.io`.
=> fix broken link in usage

jooby/pom.xml
Hello. I noticed that dependency `jakarta.ws.rs-api` is declared but not used in module `jooby`. Therefore, it makes sense to remove this dependency.
=> Remove unused dependency

jooby/src/main/resources/org/jooby/jooby.conf, jooby/src/test/java/org/jooby/test/JoobyRunner.java, modules/coverage-report/src/test/java/org/jooby/jackson/JsonCustomMapperFeature.java, modules/coverage-report/src/test/java/org/jooby/jackson/JsonDoWithFeature.java, modules/coverage-report/src/test/java/org/jooby/whoops/WhoopsTest.java, modules/jooby-assets-sass/src/test/java/org/jooby/assets/SassTest.java, modules/jooby-assets-svg-sprites/src/test/java/org/jooby/assets/SvgSpritesFileSetTest.java, modules/jooby-assets/src/test/java/org/jooby/assets/AssetCompilerTest.java
This fixes:
1. Failure to start Jooby in JoobyRunner should fail the suite early - otherwise the tests will fail later with cryptic exception `org.apache.http.conn.HttpHostConnectException: Connect to localhost:9999 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect`
2. Assets pipeline tests fail if there is no `assets.conf` in test path. Empty assets.conf seems to fix this.
3. Relax json tests to accept both "\r\n" and "\n" in output for windows(jackson seems to return platform-dependent line endings)
4. In some places(css sprites) we should not use system path separator - the css sprites results are URLS, the path separator there is always /.
In some places (tmpdir), we should use system path separator so our tests dont fail
Before the change: 9 errors, …
=> [v1] Test fixes for windows path separators, line endings

pom.xml
Version 2.0.28.Final has a vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2019-14888
=> update undertow version to 2.0.29.Final

docs/asciidoc/modules/openapi.adoc
`prepare-package` is better , with `package` phase generated files will be absent at uber-jar
=> Update openapi doc

docs/asciidoc/index.adoc
Hi @jknack,
Their is a typo (wrong URL) for `jetty` on http://jooby.io
Regards,
=> [Documentation] Wrong URL for jetty

modules/jooby-jackson/src/main/java/io/jooby/json/JacksonModule.java
This is a new way for initialising object mapper as discussed in #1677
=> jackson objectmapper initialisation new syntax

jooby/src/main/java/io/jooby/Jooby.java
This corrects the module name being used for the MVC reflection fallback being used when the module can't be found in the `ServiceLoader`.
I was running into #1390 even after the fix, and ended up finding the wrong class name suffix being used was the issue - now partial builds in IntelliJ work again :)
=> Fixed invalid module name being used for MVC reflection fallback

modules/jooby-apt/src/main/java/io/jooby/internal/apt/ParamDefinition.java, modules/jooby-apt/src/test/java/source/Controller1786.java, modules/jooby-apt/src/test/java/tests/Issue1786.java
Partially fixes issue #1786
The rest of the issue is related to non-String arguments and requires more time to think because it cannot be fixed by using the correct `ValueNode`'s method
=> Fix usage of javax.annotation.Nonnull on String args in MVC routes

docs/asciidoc/migration.adoc
This is as much work in progress as the rest of the document. 
We have 20+ applications and a pile of custom modules. We are now evaluating the upgrade path. More guidance about the missing modules i.e. how to replace the ones not directly ported would definitely be needed.
=> Add note about Maven GAV and modules

modules/jooby-bom/pom.xml, modules/jooby-commons-email/pom.xml, modules/jooby-commons-email/src/main/java/io/jooby/email/CommonsEmailModule.java, modules/jooby-commons-email/src/main/java/io/jooby/internal/email/EmailFactory.java, modules/jooby-commons-email/src/main/java/io/jooby/internal/email/HtmlEmailProvider.java, modules/jooby-commons-email/src/main/java/io/jooby/internal/email/ImageHtmlEmailProvider.java, modules/jooby-commons-email/src/main/java/io/jooby/internal/email/MultiPartEmailProvider.java, modules/jooby-commons-email/src/main/java/io/jooby/internal/email/SimpleEmailProvider.java, modules/pom.xml, pom.xml
Almost a 1:1 port of `commons-email` module from Jooby 1.x
The only change is that only the `charset` is configured by default, and it is taken directly from `application.getConfig()`.
I created a `defaults(Config appConfig)` method to populate the default config for clarity. This method also sets an `originDescription` so the source of default configuration can be easily identified.
=> Extension: commons-email from Jooby 1.x

modules/jooby-pebble/src/main/java/io/jooby/pebble/PebbleModule.java
Fixes issue when config contains `allowUnsafeMethods` option for pebble module:
```
com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path '': path has a leading, trailing, or two adjacent period '.' (use quoted "" empty string if you want an empty element)
```
=> fixed issue with pebble's allowUnsafeMethods option

jooby/src/main/java/io/jooby/Server.java
=> Print "forcibly closed by the remote host" message on debug level only

jooby/src/main/java/org/jooby/internal/RouteMetadata.java, modules/jooby-apitool/src/main/java/org/jooby/internal/apitool/TypeDescriptorParser.java, modules/jooby-bom/pom.xml, pom.xml
This PR refers to issue https://github.com/jooby-project/jooby/issues/1345 , which I posted about a year ago.
We were hoping that the issue above was resolved with 1.6.4 and revisited migrating our software to JAVA 11. Unfortunately we still got an ASM error (see issue above) with Jooby Version 1.6.7.
After some debugging we figured out that including the latest ASM dependency would not solve our problem as the ClassVisitors defined by jooby would always use ASM5. JAVA 11 however requires ASM7.
We therefore suggest to create the ClassVisitors using ASMv7. We also bumped the ASM version to the latest 7.x version.
We would really appreciate seeing that change in the next Jooby 1.x maintenance release :)
Greetings
Tobi
=> Asm support for java 11

modules/jooby-bom/pom.xml, pom.xml
=> Include 'jooby-commons-email' in dependency management.

modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/AnnotationParser.java, modules/jooby-openapi/src/test/java/issues/i1934/App1934.java, modules/jooby-openapi/src/test/java/issues/i1934/Controller1934.java, modules/jooby-openapi/src/test/java/issues/i1934/Issue1934.java
The exception was thrown because `io.jooby.internal.openapi.AnnotationParser.ParamType#CONTEXT` doesn't override `setIn(...)`.
But I guess `@ContextParam` parameters should not be part of the generated API, so I created an ignore list based on annotations.
Another possibility would be to skip based on the determined `ParamType`. I also found that although the `FORM` `ParamType` overrides `setIn(...)`, it is never called.
Could close #1934
=> Ignoring @ContextParam annotated parameters for OpenAPI

docs/asciidoc/responses.adoc, jooby/src/main/java/io/jooby/Context.java, jooby/src/main/java/io/jooby/DefaultContext.java, jooby/src/main/java/io/jooby/FileDownload.java, jooby/src/main/java/io/jooby/ForwardingContext.java, jooby/src/main/java/io/jooby/InlineFile.java, jooby/src/main/java/io/jooby/internal/HeadContext.java, jooby/src/main/java/io/jooby/internal/HttpMessageEncoder.java, jooby/src/main/java/io/jooby/internal/Pipeline.java, jooby/src/main/java/io/jooby/internal/ReadOnlyContext.java, jooby/src/main/java/io/jooby/internal/handler/SendAttachment.java, modules/jooby-test/src/main/java/io/jooby/MockContext.java, tests/src/test/java/io/jooby/FeaturedTest.java
This PR makes it possible to generate file downloads with `inline` disposition beside the existing `attachment` option. It provides a convenient API while maintains backward compatibility.
=> Allow to generate inline file downloads

docs/asciidoc/context.adoc, jooby/src/main/java/io/jooby/Jooby.java, jooby/src/main/java/io/jooby/Router.java, jooby/src/main/java/io/jooby/internal/ContextAsServiceInitializer.java, jooby/src/main/java/io/jooby/internal/Pipeline.java, jooby/src/main/java/io/jooby/internal/RouterImpl.java, jooby/src/main/java/io/jooby/internal/handler/PostDispatchInitializerHandler.java, jooby/src/test/java/io/jooby/internal/PipelineTest.java, modules/jooby-jetty/src/main/java/io/jooby/internal/jetty/JettyContext.java, tests/src/test/java/io/jooby/i1937/Issue1937.java
Closes #1937
I wrote a simple test case and discovered a problem. With Jetty it works fine but fails with Netty and Undertow (strange because I did my initial tests with Netty, and it was working fine...).
The problem is that Netty and Undertow dispatches the execution to a worker thread. The thread local is initialized by the event loop thread, but then the service registry is queried by the worker thread -> not found.
Do you have an idea how to resolve this?
=> Ability to access the current context via the service registry

modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/ClientReference.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/SecurityFilterImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/pac4j/Pac4jModule.java
May close #1908 
I tried to solve it in a way that only minor modifications are necessary in the existing code and logic.
<details>
<summary>Click for test application.</summary>
```java
package demo;
import io.jooby.Context;
import io.jooby.Jooby;
import io.jooby.di.GuiceModule;
import io.jooby.pac4j.Pac4jModule;
import org.pac4j.core.exception.CredentialsException;
import org.pac4j.core.profile.CommonProfile;
import org.pac4j.http.client.direct.ParameterClient;
import javax.inject.Inject;
import javax.inject.Provider;
public class Pac4JTest extends Jooby {
{
install(new GuiceModule());
setContextAsService(true);
get("/unprotected", ctx -> "unprotected");
install(new Pac4jModule().client(CustomClient.class));
get("/protected", ctx -> "protected");
}
static class CustomClient extends …
```
=> Allow to specify pac4j clients as classes and utilize DI

jooby/src/main/java/io/jooby/internal/ContextAsServiceInitializer.java, tests/pom.xml, tests/src/test/java/io/jooby/i1937/Issue1937.java
I found out that when Guice the module is installed and someone tries to fetch the `Context` outside of a request (with `setContextAsService(true)`) `Jooby.require(Context.class)` returns with `null` instead of throwing an exception. This breaks the `@Nonnull` contract of this method.
**Without** Guice it works as expected:
- `require(...)` tries the Service Registry
- finds the provider, calls it, `null` is returned
- `require(...)` tries the DI registry, but there is none
- throws `RegistryException`
**With** Guice it breaks:
- `require(...)` tries the Service Registry
- finds the provider, calls it, `null` is returned
- `require(...)` tries the DI registry, finds Guice registry, calls it
- Guice registry finds the provider since it was taken over from the Service Registry at startup
- …
=> Throw an exception on attempt to inject Context out of scope

modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/UrlResolverImpl.java, tests/src/test/java/io/jooby/Issue1990.java
May close #1990
I had no better idea than generating the URL from scratch, with code similar to `DefaultContext#getRequestPath(String)`
=> Allow to resolve URLs with context = null

docs/asciidoc/static-files.adoc, jooby/src/main/java/io/jooby/AssetHandler.java, jooby/src/main/java/io/jooby/CacheControl.java, tests/src/test/java/io/jooby/FeaturedTest.java
We used `AssetHandler` to serve a single page app and it does it great. However we would like to specify alternative cache header config for specific assets. We also need to explicitly disable caching completely for some assets. Currently we use our own asset handler implementation for this.
I created this PR as a basis of discussion for a possible feature for the above functionality in Jooby.
The API could be something like this:
```java
new AssetHandler(source)
.cacheControl(path -> path.endsWith("about.html"), cacheControl.setNoCache())
.cacheControl("foo.js", cacheControl -> cacheControl.maxAge(3600).setETag(false))
```
The current changes are a proof of concept and are fully backwards compatible.
=> Advanced cache control for AssetHandler

docs/asciidoc/context.adoc, jooby/src/main/java/io/jooby/Cookie.java, jooby/src/main/java/io/jooby/DefaultContext.java, jooby/src/main/java/io/jooby/Jooby.java, jooby/src/main/java/io/jooby/Router.java, jooby/src/main/java/io/jooby/SameSite.java, jooby/src/main/java/io/jooby/internal/RouterImpl.java, jooby/src/test/java/io/jooby/CookieTest.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/WebContextImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/pac4j/Pac4jModule.java, modules/jooby-pac4j/src/main/java/io/jooby/pac4j/Pac4jOptions.java, tests/src/test/java/io/jooby/FeaturedTest.java
May close #1998
This PR contains the possible API changes. This should not change anything on the current behavior unless someone sets the parameter explicitly.
We should now decide whether to apply this on any of jooby's cookies (session, flash, pac4j maybe)?
- [DefaultContext](https://github.com/jooby-project/jooby/blob/d6fbe9b552501240719c5ee9c9fe698a059c8ad7/jooby/src/main/java/io/jooby/DefaultContext.java#L95)
- [SessionToken](https://github.com/jooby-project/jooby/blob/d6fbe9b552501240719c5ee9c9fe698a059c8ad7/jooby/src/main/java/io/jooby/SessionToken.java#L131)
- [WebContextImpl](https://github.com/jooby-project/jooby/blob/d6fbe9b552501240719c5ee9c9fe698a059c8ad7/modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/WebContextImpl.java#L115)
In Play Framework they use `Lax` by …
=> Cookie API now supports the SameSite parameter

modules/jooby-apt/src/main/java/io/jooby/internal/apt/ModuleCompiler.java, modules/jooby-apt/src/test/java/tests/i1859/Issue1859.java, modules/jooby-apt/src/test/java/tests/i2026/C2026.java, modules/jooby-apt/src/test/java/tests/i2026/Expected2026.java, modules/jooby-apt/src/test/java/tests/i2026/Issue2026.java
Before: `"(Lio/jooby/Jooby;Ljavax/inject/Provider<tests.i2026.C2026>;)V"`
After: `"(Lio/jooby/Jooby;Ljavax/inject/Provider<Ltests/i2026/C2026;>;)V"`
Fix #2026
=> MVC: wrong method signature

docs/asciidoc/servers.adoc, jooby/src/main/java/io/jooby/ServerOptions.java, jooby/src/main/java/io/jooby/SslOptions.java, jooby/src/test/java/io/jooby/SslOptionsTest.java, modules/jooby-freemarker/src/test/java/io/jooby/freemarker/FreemarkerModuleTest.java, modules/jooby-jetty/src/main/java/io/jooby/jetty/Jetty.java, modules/jooby-netty/src/main/java/io/jooby/netty/Netty.java, modules/jooby-utow/src/main/java/io/jooby/utow/Utow.java
- Set default protocol to `TLSv1.2, TLSv1.3`
- If a listed protocol is not supported, it is ignored; however, if you specify a list of protocols, none of which are supported, an exception will be thrown.
- Turn off TLSv1 and TLSv1.1 in Jetty
- Fix date tests failure
=> SSL: configure protocol

docs/asciidoc/modules/rocker.adoc, modules/jooby-bom/pom.xml, modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyContext.java, modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyHandler.java, modules/jooby-rocker/src/main/java/io/jooby/rocker/ByteBufferOutput.java, modules/jooby-rocker/src/main/java/io/jooby/rocker/RockerHandler.java, modules/jooby-rocker/src/main/java/io/jooby/rocker/RockerMessageEncoder.java, modules/jooby-rocker/src/main/java/io/jooby/rocker/RockerModule.java, modules/jooby-rocker/src/main/java/io/jooby/rocker/RockerResponseHandler.java, modules/jooby-utow/src/main/java/io/jooby/internal/utow/UtowContext.java, modules/jooby-utow/src/main/java/io/jooby/internal/utow/UtowHandler.java
- Replace the StringBuilder output with a byte buffer array
- Byte buffer need to be sized properly to reduce re-allocation and copy
- Default buffer size is 4k
- There is an option to reuse/recycle a byte buffer using a thread local mechanism
- Extra: micro optimization around incoming requests: Ignore HTTP body on GET requests
=> Rocker: move from string builder to byte array

modules/jooby-openapi/pom.xml, modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/ConflictiveSetter.java, modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/ParserContext.java
- Add a rule to favor List over Array([]) on setters
- Affects SslOptions.setProtocol, Jooby.setLocales
- Not sure why previous version ignore Jooby classes and this one doesn't (2.0.23)
- Get back build
fix #2137
=> openapi/swagger: Conflicting setter definitions for property

modules/jooby-netty/src/main/java/io/jooby/internal/netty/HttpRawPostRequestDecoder.java, modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyHandler.java
- Clean up thread local request references used by DefaultHttpDataFactory
- This was causing some io.netty.handler.codec.DefaultHeaders$HeaderEntry to leak
- Fix works, but not sure how to write a test to demonstrate
Fixes #2167
=> netty: Fix memory leak on HTTP post

docs/asciidoc/servers.adoc, jooby/pom.xml, jooby/src/main/java/io/jooby/ServerOptions.java, jooby/src/main/java/io/jooby/SslProvider.java, jooby/src/main/java/io/jooby/internal/SslX509Provider.java, modules/jooby-conscrypt/pom.xml, modules/jooby-conscrypt/src/main/java/io/jooby/conscrypt/ConscryptSslProvider.java, modules/jooby-conscrypt/src/main/resources/META-INF/services/io.jooby.SslProvider, modules/jooby-http2-jetty/pom.xml, modules/jooby-http2-jetty/src/main/java/io/jooby/internal/jetty/JettyHttp2Configurer.java, modules/jooby-jetty/src/main/java/io/jooby/jetty/Jetty.java, modules/jooby-utow/src/main/java/io/jooby/internal/undertow/ConscriptAlpnProvider.java, modules/jooby-utow/src/main/resources/META-INF/services/io.undertow.protocols.alpn.ALPNProvider, modules/pom.xml, pom.xml
- OpenSSL option across 3 web-server implementation
- Conscrypt(boring-ssl) provider implemenation for OpenSSL version (via ServiceLoader: jooby-conscrypt)
- Netty/Undertow still works with both JDK-SSL/OpenSSL version, while Jetty only works with OpenSSL
Fixes #2194
/cc @hc-codersatlas
=> SSL: Conscrypt provider

jooby/src/main/java/io/jooby/Server.java, modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyWebSocket.java, modules/jooby-utow/src/main/java/io/jooby/internal/utow/UtowWebSocket.java
- Netty: fix NPE when there is no message callback
- Undertow: fix double close event fired
- Undertow: silent connection reset exception while closing browser tab
Fixes #2210
=> WebSocket enhancements

jooby/src/main/kotlin/io/jooby/CoroutineRouter.kt, jooby/src/main/kotlin/io/jooby/internal/mvc/CoroutineLauncher.kt, jooby/src/test/kotlin/io/jooby/CoroutineRouterTest.kt
Make it possible to redefine coroutine context for every launch to be able to properly implement suspend/restore of additional state, e.g. MDC, transactions, etc
Fixes #2257
=> Flexible coroutine context

jooby/src/main/java/io/jooby/Value.java
`ctx.session().get("example").isPresent()` is more readable than `!ctx.session().get("example").isMissing()`
=> Added Value#isPresent

modules/jooby-banner/pom.xml, modules/jooby-caffeine/pom.xml, modules/jooby-commons-email/pom.xml, modules/jooby-guice/pom.xml
The mockito dependency is not needed in production code and should not be
consumed by consuming applications.
=> Add test scope to usages of mockito-core in jooby modules

docs/asciidoc/responses.adoc, jooby/src/main/kotlin/io/jooby/CoroutineRouter.kt, jooby/src/main/kotlin/io/jooby/HandlerContext.kt, jooby/src/main/kotlin/io/jooby/Kooby.kt, jooby/src/main/kotlin/io/jooby/internal/mvc/CoroutineLauncher.kt, jooby/src/test/kotlin/io/jooby/CoroutineRouterTest.kt
Reasons:
1. Extra coroutine context often needs to access Jooby Context
2. Relying on users to extend the default CoroutineContext can be error prone - users can forget to include the ExceptionHandler, resuling in "hanging" asynchronous requests
Signature of launchContext lambda has changed in not 100%-compatible way, but as launchContext was a recent new feature and wasn't yet documented, probably backwards-compatibility with previous API is not needed.
=> Improve coroutine context redefinition introduced in Jooby 2.9.6

docs/asciidoc/modules/jsonb.adoc, docs/asciidoc/modules/modules.adoc, modules/jooby-bom/pom.xml, modules/jooby-jsonb/pom.xml, modules/jooby-jsonb/src/main/java/io/jooby/json/JsonbModule.java, modules/jooby-jsonb/src/test/java/io/jooby/json/JsonbModuleTest.java, modules/pom.xml, pom.xml
Adds yasson dependecy as the implementation for JSON Binding.
There was a previous similar addition for jooby 1 that was not included in jooby 2:
https://github.com/jooby-project/jooby/pull/1248
https://jooby.io/v1/doc/yasson/
=> Adds support for JSON-B (JSR 367)

docs/asciidoc/modules/spring.adoc, docs/asciidoc/servers.adoc
Updated the servers documentation to include configuration for Mutual TLS (trust certificate, password and client authentication).  Also fixed some minor copy/paste errors in the existing documentation.  Addresses Issue #2371
=> Issue 2371 ssl configuration incomplete in application.conf

modules/jooby-netty/src/main/java/org/jooby/internal/netty/NettyPush.java
Fixes #2252 for the 1.x branch. As such it has the same effect as b66e3342cf95205324023cfdf2cb5811e8a6dcf4 had for the 2.x branch.
=> Validate HTTP headers in Netty

docs/asciidoc/modules/modules.adoc, docs/asciidoc/modules/yasson.adoc, modules/jooby-bom/pom.xml, modules/jooby-yasson/pom.xml, modules/jooby-yasson/src/main/java/io/jooby/json/YassonModule.java, modules/jooby-yasson/src/test/java/io/jooby/json/YassonModuleTest.java, modules/pom.xml, pom.xml
There was a previous similar addition for jooby 1 that was not included in
jooby 2:
https://github.com/jooby-project/jooby/pull/1248
https://jooby.io/v1/doc/yasson/
this pull request replaces #2368
=> Adds support for JSON-B (JSR 367) using yasson as the implementation.

modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyPipeline.java, modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyWebSocketCompressor.java
In previous PR #2377 it was enabled only for HTTP 2.
Original issue: #2364
=> Enable netty ws compression for HTTP 1.1

jooby/src/main/kotlin/io/jooby/Kooby.kt, modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/AnnotationParser.java, modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/ParserContext.java
This fixes the latest Jooby 2.11.0:
1. It seems that newer Kotlin compiler (e.g. 1.5.30, with IR backend) sometimes names the Continuation parameter as `$completion` in suspending functions. Let's add support for it, or otherwise OpenAPI generation crashes with messages that parameter type cannot be found for `$completion`.
2. Not related to Kotlin: do not crash when routes have LocalDate, LocalDateTime, Instant, etc parameters - use the correct DateSchema or DateTimeSchema for these.
Having these fixes, we now can successfully generate openapi spec for our project. Without these fixes, openapi crashes with mostly meaningless error messages, like in issue #1805
=> Fix OpenAPI generation for newer Kotlin compiler and support java.time types

pom.xml
Reference: https://in.relation.to/2021/09/14/ready-for-jdk17/
=> Upgrade to Hibernate 5.5.7 for best Java 17 support

modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/ParserContext.java
This pull requests contains two fixes when generating the openapi defintion using jooby-openapi:
**Fix for Map:**
According to https://swagger.io/docs/specification/data-models/dictionaries/ a map should be represented by a schema that has the type as well as an additionalProperties element with the type property set to the value property of the map.
So the following map
```
{
"en": "English",
"fr": "French"
}
```
should become the following schema:
```
type: object
additionalProperties:
type: string
```
**Fix for byte[]:**
There exists a special ByteArraySchema class that can be used in this case, as it produces the correct schema for it:
```
schema": {
"type": "string",
"format": "byte"
}
```
=> Fix Map and byte[] for openapi

modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/OpenAPIParser.java
Schemas can have an annotation stating that they are nullable.
This fix uses a possibly set nullable field for the resulting OpenAPI description.
=> Add support for nullable schema field for Openapi generation

modules/jooby-gson/src/main/java/io/jooby/json/GsonModule.java
Close #2560
At the moment, the GsonModule only encodes using UTF-8. With this change, UTF-8 is also used during decoding which solves problems with weirds looking strings.
=> Fix GsonModule to also use UTF-8 encoding while decoding

docs/asciidoc/servers.adoc, jooby/src/main/java/io/jooby/Jooby.java, jooby/src/main/java/io/jooby/ServerOptions.java, jooby/src/test/java/io/jooby/ServerOptionsTest.java, modules/jooby-jetty/src/main/java/io/jooby/jetty/Jetty.java, modules/jooby-netty/src/main/java/io/jooby/netty/Netty.java, modules/jooby-utow/src/main/java/io/jooby/utow/Utow.java, tests/src/test/java/io/jooby/HttpsTest.java
Fixes #2569. There was also a small fix for the documentation for kotlin server config, the boolean properties were missing the `is` prefix.
=> Add httpsOnly option

.github/workflows/quick-build.yml, .github/workflows/starter.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

modules/jooby-maven-plugin/src/main/java/io/jooby/maven/RunMojo.java, modules/jooby-run/src/main/java/io/jooby/run/JoobyRun.java, modules/jooby-run/src/main/java/io/jooby/run/JoobyRunOptions.java
This is a fix for #2577 
I tested it on Eclipse and the defaults seem good for our projects.
=> Add a queue for hotreload to group changes to fix #2577

docs/asciidoc/servers.adoc
`server.ssl.httpsOnly` doesn't do anything, the code references `server.httpsOnly`, so fix the docs.
=> Fix httpsOnly config file example

jooby/src/main/java/io/jooby/internal/HttpMessageEncoder.java, tests/src/test/java/io/jooby/i2804/Issue2804.java
fixes #2804
Fixes regression introduced by 9640984a949890948f15c472e47df3086005b890 to fix issue #2613 internal.HttpMessageEncoder should consider the Route produces for determining MediaType
=> encoder: should consider all produce types before default TO_STRING

modules/jooby-jstachio/src/main/java/io/jooby/jstachio/ByteBufferedOutputStream.java, modules/jooby-jstachio/src/main/java/io/jooby/jstachio/JStachioBuffer.java, modules/jooby-jstachio/src/main/java/io/jooby/jstachio/JStachioHandler.java, modules/jooby-jstachio/src/main/java/io/jooby/jstachio/JStachioMessageEncoder.java, modules/jooby-jstachio/src/main/java/io/jooby/jstachio/JStachioModule.java, modules/jooby-jstachio/src/main/java/io/jooby/jstachio/JStachioRenderer.java, modules/jooby-jstachio/src/main/java/io/jooby/jstachio/JStachioResultHandler.java, pom.xml
@jknack I have updated the JStachio module so that it can take advantage of pre-encoding (the static parts of the template are generated as bytes[] in advance).
The reason I did this is that in the techempower benchmarks Rocker performed better than JStachio's naive `String.getBytes()`.
I also have added threadlocal buffering and removed setting charset.
Setting the charset was a bad idea anyway as JStachio unlike others cannot always re-read the template from the filesystem furthermore escaping is naturally tied to charset.
I noticed that Rocker just assumes MediaType.html (and thus UTF-8) so I have done likewise.
I just released jstachio 0.17.0 but it will take an hour or so before central shows it.
=> Add Rocker style pre-encoding for JStachio

docs/asciidoc/configuration.adoc
Added a table with a short description and default value for application properties, as discussed in issue #2981.
=> Add information about application properties used by Jooby in the documentation

docs/src/main/java/io/jooby/adoc/JavadocProcessor.java
Links to javadoc in the documentation are not working. This should fix them.
=> doc: fix javadoc links

jooby/src/main/java/io/jooby/Router.java
This will make it impossible for zero asset sources.
In theory this will break semver API but I know this is the right way and we don't follow semver :P 
Ideally this would be on the AssetHandler as well.
For the odd place where someone actually passes an array you can add an additional method:
```java
default @NonNull Route assets(@NonNull String pattern, @NonNull AssetSource[] sources)
```
Let me know and I can add that as well.
=> Improve asset API

docs/asciidoc/getting-started.adoc
Thanks for a very cool project!
I am currently evaluating Jooby for my workplace, and when reading through the docs (which I believe are generally good) I noticed some grammatical errors. I think it would be a shame if these errors were to cast a shadow over such a cool framework, so I cleaned up the "Getting Started" part of the docs as a first effort. If you like these changes, I can go through the rest of the docs later if you'd like.
=> Cleaned up "Getting Started" docs

pom.xml
=> Bump ASM from 9.3 to 9.6 to enable support for Java 21

docs/asciidoc/di-dagger.adoc, docs/asciidoc/getting-started.adoc
*  Add note about what java version needs to be used when running the cli
* Update dagger section with up-do-date kotlin information (use kapt)
=> Cleanup starting and dagger docs

docs/asciidoc/testing.adoc
From `io.jooby.MockRouter` to `io.jooby.test.MockRouter`
=> :scroll: Fixed imports of MockRouter in docs

docs/asciidoc/templates.adoc, jooby/src/main/java/io/jooby/MapModelAndView.java, jooby/src/main/java/io/jooby/ModelAndView.java, modules/jooby-freemarker/src/main/java/io/jooby/freemarker/FreemarkerTemplateEngine.java, modules/jooby-freemarker/src/test/java/io/jooby/freemarker/FreemarkerModuleTest.java, modules/jooby-handlebars/src/main/java/io/jooby/internal/handlebars/HandlebarsTemplateEngine.java, modules/jooby-handlebars/src/test/java/io/jooby/handlebars/HandlebarsModuleTest.java, modules/jooby-jte/src/main/java/io/jooby/jte/JteTemplateEngine.java, modules/jooby-pebble/src/main/java/io/jooby/pebble/PebbleTemplateEngine.java, modules/jooby-pebble/src/test/java/io/jooby/pebble/PebbleModuleTest.java, modules/jooby-thymeleaf/src/main/java/io/jooby/internal/thymeleaf/ThymeleafTemplateEngine.java, tests/src/test/java/io/jooby/test/FeaturedTest.java, tests/src/test/java/io/jooby/test/TemplateEngineTest.java
- Allow to use anything as Model
- Remove `put()` methods from ModelAndView
- Introduce `MapModelAndView`
- Replace `new ModelAndView(String, Map)` by `ModelAndView.map()`
- fix #3113
=> template engine: ModelAndView that is not a Map

jooby/src/main/java/io/jooby/MediaType.java
Send `application/wasm` for `*.wasm` files.
=> Support correct mime type for .wasm files fix #3403

modules/jooby-avaje-inject/pom.xml, modules/jooby-avaje-inject/src/main/java/io/jooby/avaje/inject/AvajeInjectModule.java, modules/jooby-avaje-inject/src/test/java/io/jooby/avaje/inject/AvajeInjectModuleTest.java, modules/jooby-avaje-inject/src/test/java/io/jooby/avaje/inject/app/Controller.java, modules/jooby-avaje-inject/src/test/java/io/jooby/avaje/inject/app/TestApp.java
@jknack 
AvajeInjectModule seems doesn't work as expected, at least for me.
With a very basic example (reproduced in test https://github.com/jooby-project/jooby/commit/c9c81fdc85470df43b086abb257d611a6fd0574a) Jooby inner services injection fails with class cast exception, for example `JsonMapper`:  
```text
Caused by: java.lang.ClassCastException: class io.jooby.internal.ServiceRegistryImpl$$Lambda$458/0x0000000800dbf350 cannot be cast to class com.fasterxml.jackson.databind.json.JsonMapper (io.jooby.internal.ServiceRegistryImpl$$Lambda$458/0x0000000800dbf350 and com.fasterxml.jackson.databind.json.JsonMapper are in unnamed module of loader 'app')
```
I assume this is due to the fact that services already wrapped into lambda in `singletone()` …
=> Fix avaje module

jooby/src/main/java/io/jooby/ServerOptions.java, jooby/src/main/java/io/jooby/SslOptions.java, tests/src/test/java/io/jooby/test/HttpsTest.java
=> Add custom SSL context option

jooby/src/main/java/io/jooby/internal/RouterImpl.java, tests/pom.xml, tests/src/test/java/io/jooby/i3400/Issue3400.java, tests/src/test/java/io/jooby/i3400/Pet3400.java, tests/src/test/java/io/jooby/i3500/Issue3500.java, tests/src/test/java/io/jooby/i3500/Widget.java, tests/src/test/java/io/jooby/i3500/WidgetService.java
=> 415 unsupported media type when using mount to add routes

docs/asciidoc/modules/db-scheduler.adoc, docs/asciidoc/modules/modules.adoc, docs/asciidoc/templates.adoc, docs/pom.xml, docs/src/main/java/io/jooby/adoc/DocGenerator.java, modules/jooby-bom/pom.xml, modules/jooby-db-scheduler/pom.xml, modules/jooby-db-scheduler/src/main/java/io/jooby/dbscheduler/BeanTasks.java, modules/jooby-db-scheduler/src/main/java/io/jooby/dbscheduler/DbScheduleParser.java, modules/jooby-db-scheduler/src/main/java/io/jooby/dbscheduler/DbSchedulerApp.java, modules/jooby-db-scheduler/src/main/java/io/jooby/dbscheduler/DbSchedulerModule.java, modules/jooby-db-scheduler/src/main/java/io/jooby/dbscheduler/DbSchedulerProperties.java, modules/jooby-db-scheduler/src/main/java/io/jooby/dbscheduler/Scheduled.java, modules/jooby-db-scheduler/src/main/java/io/jooby/dbscheduler/package-info.java, modules/jooby-db-scheduler/src/main/java/io/jooby/internal/dbscheduler/ClassLoaderJavaSerializer.java, modules/jooby-db-scheduler/src/main/java/io/jooby/internal/dbscheduler/DbTable.java, modules/jooby-db-scheduler/src/main/java/module-info.java, modules/jooby-db-scheduler/src/test/java/io/jooby/dbscheduler/SchedulerParserTest.java, modules/pom.xml
=> scheduler: add db-scheduler module

modules/jooby-avaje-validator/src/main/java/io/jooby/avaje/validator/AvajeValidatorModule.java, modules/jooby-avaje-validator/src/main/java/io/jooby/avaje/validator/ConstraintViolationHandler.java, modules/jooby-avaje-validator/src/main/java/io/jooby/avaje/validator/package-info.java, modules/jooby-hibernate-validator/src/main/java/io/jooby/hibernate/validator/ConstraintViolationHandler.java, modules/jooby-hibernate-validator/src/main/java/io/jooby/hibernate/validator/HibernateValidatorModule.java, modules/jooby-hibernate-validator/src/main/java/io/jooby/hibernate/validator/package-info.java
- make constrainctvalidation cast safe
- use config api for properties
@SentryMan can you look at locales?
=> validation: cleanup

jooby/src/main/java/io/jooby/Context.java, jooby/src/main/java/io/jooby/Value.java, jooby/src/main/java/io/jooby/internal/HashValue.java, jooby/src/main/java/io/jooby/internal/HeadersValue.java, tests/src/test/java/io/jooby/test/Issue2357.java
Makes all ways to work with headers consistent and comply with the HTTP Headers RFC.
Continues from #2358 
Replaces #3517
=> Fixes case insensitive headerMap and header toMultimap

docs/asciidoc/context.adoc, modules/jooby-apt/pom.xml, modules/jooby-apt/src/main/java/io/jooby/internal/apt/MvcParameter.java, modules/jooby-apt/src/main/java/io/jooby/internal/apt/ParameterGenerator.java, modules/jooby-apt/src/main/java/io/jooby/internal/apt/Types.java, modules/jooby-apt/src/test/java/tests/validation/BeanValidationsController.java, modules/jooby-apt/src/test/java/tests/verifyarg/ControllerCookie.java, modules/jooby-apt/src/test/java/tests/verifyarg/ControllerFlash.java, modules/jooby-apt/src/test/java/tests/verifyarg/ControllerFlashOpt.java, modules/jooby-apt/src/test/java/tests/verifyarg/ControllerHeader.java, modules/jooby-apt/src/test/java/tests/verifyarg/ControllerSession.java, modules/jooby-apt/src/test/java/tests/verifyarg/VerifyArgTypeTest.java, pom.xml
=> cleanup validation tests

modules/jooby-avaje-inject/src/main/java/io/jooby/avaje/inject/AvajeInjectModule.java
It might be a handy thing to inject.
related to #3544
=> Add `Environment` to Avaje `BeanScope`

docs/asciidoc/modules/avaje-validator.adoc, docs/asciidoc/modules/hibernate-validator.adoc, docs/asciidoc/problem-details.adoc, jooby/src/main/java/io/jooby/Jooby.java, jooby/src/main/java/io/jooby/internal/RouterImpl.java, jooby/src/main/java/io/jooby/problem/HttpProblem.java, jooby/src/main/java/io/jooby/problem/ProblemDetailsHandler.java, jooby/src/main/java/io/jooby/validation/JsonPointer.java, jooby/src/main/java/io/jooby/validation/ValidationResult.java, modules/jooby-avaje-validator/src/main/java/io/jooby/avaje/validator/AvajeValidatorModule.java, modules/jooby-avaje-validator/src/main/java/io/jooby/avaje/validator/ConstraintViolationHandler.java, modules/jooby-hibernate-validator/src/main/java/io/jooby/hibernate/validator/ConstraintViolationHandler.java, modules/jooby-hibernate-validator/src/main/java/io/jooby/hibernate/validator/HibernateValidatorModule.java, tests/src/test/java/io/jooby/i3508/App3508.java, tests/src/test/java/io/jooby/i3508/Controller3508.java, tests/src/test/java/io/jooby/i3508/Issue3508.java, tests/src/test/java/io/jooby/i3508/Issue3508ProblemDetails.java, tests/src/test/java/io/jooby/problem/data/App.java
While was working on problem details support in validation modules the general concept a bit changed.  
Enabling the `ProblemDetailsHandler` moved to the `hocon` configuration.
1. It greatly simplifies the integration of problem details in modules. Modules can now detect if `ProblemDetailsHandler` is enabled at an early stage of the module initiation. With the previous approach, it would have been much harder and might have led to implementing awkward solutions.
2. An additional benefit of the new approach is that `ProblemDetailsHandler` will be automatically registered as the last handler in the error handlers chain, so dev no longer need to worry about that.
So, to enable `ProblemDetailsHandler` the next config now required:
```hocon
problem.details {
enable: true
muteCodes: [401, 106] …
```
=> problem details in modules

jooby/src/main/java/io/jooby/OpenAPIModule.java
closes https://github.com/jooby-project/jooby/issues/3559
my suggestion here is to simplify module logic and make it independent from `Jooby.getName()`, so it always matches the logic of `OpenApiGenerator.export()` relying on class name only.
=> fix misleading openapi application name

docs/asciidoc/modules/avaje-inject.adoc, docs/asciidoc/modules/avaje-validator.adoc, docs/asciidoc/mvc-api.adoc, modules/jooby-cli/src/main/resources/cli/pom.xml.hbs
After `jooby-apt` rewrite the annotation-processors order becomes quite important. Added a note in the docs to save some brain cells for newbies.
=> annotation processors order note

modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/CallbackFilterImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/ContextFactoryImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/GrantAccessAdapterImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/LogoutImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/Pac4jCurrentUser.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/SavedRequestHandlerImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/SecurityFilterImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/SessionStoreFactoryImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/WebContextImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/pac4j/Pac4jFrameworkParameters.java, modules/jooby-pac4j/src/main/java/io/jooby/pac4j/Pac4jModule.java, modules/jooby-pac4j/src/main/java/io/jooby/pac4j/Pac4jOptions.java, pom.xml, tests/src/test/java/io/jooby/test/Issue3328.java
=> pac4j: upgrade to 6.x

modules/jooby-openapi/src/test/java/issues/Issue1582.java
this will avoid publishing test code to Maven Central, as found while rebuilding releases for Reproducible Central:
https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/io/jooby/README.md
see more precisely https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/io/jooby/jooby-project-3.3.1.diffoscope
=> generate test code to target/test-classes

docs/asciidoc/modules/hibernate-validator.adoc, modules/jooby-hibernate-validator/src/main/java/io/jooby/hibernate/validator/HibernateValidatorModule.java, modules/jooby-hibernate-validator/src/main/java/io/jooby/internal/hibernate/validator/CompositeConstraintValidatorFactory.java, modules/jooby-hibernate-validator/src/main/java/io/jooby/internal/hibernate/validator/RegistryConstraintValidatorFactory.java, modules/jooby-hibernate/src/main/java/io/jooby/hibernate/HibernateModule.java, modules/jooby-jetty/src/main/java/io/jooby/jetty/JettyServer.java
- simplify custom ConstraintValidatorFactory based on DI as well as manually created factories
- integrates Validator factory into hibernate
=> hibernate-validator: better support for custom ConstraintValidatorFactory

modules/jooby-flyway/src/main/java/io/jooby/flyway/FlywayModule.java
With configuration like: 
```
flyway.run=[baseline, migrate]
```
application will crash with message '_Unknown flyway command: baseline_' but still provide baseline to db. So we need a fix)
=> fix flyway baseline

docs/asciidoc/packaging/packaging.adoc, docs/src/main/java/io/jooby/adoc/DocGenerator.java, docs/src/main/java/io/jooby/adoc/DocPostprocessor.java, docs/src/main/java/io/jooby/adoc/JoobyExtensionRegistry.java
I noticed that the subsection [MVC API - Execution Model](https://jooby.io/#mvc-api-execution-model) was being used as the anchor link in the content for the [Execution Model](https://jooby.io/#execution-model) heading.
I think this is due to the `tocItems` method updating all links in the documents when the id changes rather than just those within it's element
https://github.com/jooby-project/jooby/blob/5e345b59719ad18317ada7e2a7928e164d611e07/docs/src/main/java/io/jooby/adoc/DocGenerator.java#L411-L420
I have updated this method to use `h` rather than `doc` and from what I can tell from a manual pass through, all links seem to work.
I've also moved the post processing functionality to make use of the inbuilt AsciiDoctorJ [post processing …
=> Fix anchor links being overwritten

docs/asciidoc/problem-details.adoc, docs/pom.xml, docs/src/main/java/io/jooby/adoc/DocApp.java, jooby/src/main/java/io/jooby/problem/HttpProblem.java
@jknack Hope you don't mind adding a couple of shorthands for the most common validation codes for brevity
=> [HttpProblem] common validation shorthands

modules/jooby-apt/src/main/resources/io/jooby/internal/apt/Source.java, tests/src/test/java/io/jooby/i3756/C3756.java, tests/src/test/java/io/jooby/i3756/S3756.java
Let me know if you want the PR to target main or 3.x
This just adds the test module.
```
[ERROR] /Users/agent/projects/jooby/modules/jooby-apt-tests/target/generated-test-sources/test-annotations/tests/i3756/C3756_.java:[16,9] reference to C3756_ is ambiguous
[ERROR]   both constructor C3756_(tests.i3756.S3756) in tests.i3756.C3756_ and constructor C3756_(java.util.function.Function<io.jooby.Context,tests.i3756.C3756>) in tests.i3756.C3756_ match
```
=> Add cast of lambda constructor to jooby-apt to fix ambiguous compiler error  #3756
