jooby-project/jooby

jooby-jade/README.md, jooby-jade/pom.xml, jooby-jade/src/main/java/org/jooby/jade/Engine.java, jooby-jade/src/main/java/org/jooby/jade/Jade.java, jooby-jade/src/test/java/org/jooby/jade/JadeEngineTest.java, jooby-jade/src/test/java/org/jooby/jade/JadeTest.java, md/doc/jade/README.md, pom.xml
Using jade4j as an alternative renderer
=> Add jade renderer

jooby-hotreload/src/main/java/org/jooby/hotreload/AppModule.java
This pull request is focused on resolving occurrences of Sonar rules
squid:CommentedOutCodeLine - Sections of code should not be "commented out".
squid:S1066 - Collapsible "if" statements should be merged.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:CommentedOutCodeLine
https://dev.eclipse.org/sonar/rules/show/squid:S1066
Please let me know if you have any questions.
George Kankava
=> Multiple code improvements - squid:CommentedOutCodeLine, squid:S1066

md/gradle.md
It does not contains much for now, but it is a base to build on.
=> Add minimal documentation for Gradle

jooby/src/main/java/org/jooby/handlers/AssetHandler.java, md/routes.md
=> Cleaned up http addresses.

pom.xml
=> Security issue: upgrade to pac4j v1.9.4

coverage-report/src/test/java/org/jooby/issues/PullRequest583Test.java, coverage-report/src/test/java/org/jooby/issues/PullRequest583WithChildInjectorTest.java, jooby/src/main/java/org/jooby/Jooby.java
This will help me a lot.
I am embedding Jooby into a Guice based Swing application.
Being able to create a child injector will be of great help.
=> extract #createInjector

jooby-ebean/src/main/java/org/jooby/ebean/Ebeanby.java, jooby-ebean/src/test/java/org/jooby/ebean/Issue589.java
=> Deadlock with shutdown fix #589

jooby-swagger/README.md
the usage example with Swagger() confused me and burned a few minutes
=> replace Swagger with SwaggerUI

coverage-report/src/test/java/org/jooby/issues/Issue636.java, jooby-netty/src/main/java/org/jooby/internal/netty/NettyHandler.java, jooby/src/main/java/org/jooby/Err.java, jooby/src/main/java/org/jooby/WebSocket.java, jooby/src/main/java/org/jooby/internal/ConnectionResetByPeer.java, jooby/src/main/java/org/jooby/internal/WebSocketImpl.java, jooby/src/test/java/org/jooby/ErrTest.java, jooby/src/test/java/org/jooby/WebSocketTest.java, jooby/src/test/java/org/jooby/internal/ConnectionResetByPeerTest.java, jooby/src/test/java/org/jooby/internal/WebSocketImplTest.java
=> WebSockets: #isOpen fix #574

coverage-report/pom.xml, jooby-ebean/pom.xml, jooby-ebean/src/main/java/org/jooby/ebean/Ebeanby.java, jooby-ebean/src/main/java/org/jooby/internal/ebean/EbeanEnhancer.java, jooby-ebean/src/main/java/org/jooby/internal/ebean/EbeanManaged.java, jooby-ebean/src/test/java/org/jooby/ebean/EbeanbyTest.java, jooby-ebean/src/test/java/org/jooby/internal/ebean/EbeanManagedTest.java, pom.xml
Here your work @huysamen work. Thank you.
=> Updates Ebean to latest versions (10.x)

coverage-report/pom.xml, jooby-cassandra/pom.xml, jooby-cassandra/src/main/java/org/jooby/cassandra/Cassandra.java, jooby-cassandra/src/test/java/org/jooby/cassandra/CassandraTest.java, md/doc/cassandra/cassandra.md
=> Datastax DSE a Separate Module fix #653

jooby-dist/src/main/resources/assemblies/jooby.war.xml, jooby-jetty/src/test/java/org/jooby/internal/jetty/JettyHandlerTest.java, jooby-servlet/src/main/java/org/jooby/servlet/ServletServletRequest.java, jooby-servlet/src/main/java/org/jooby/servlet/ServletServletResponse.java, jooby-servlet/src/test/java/org/jooby/servlet/ServletServletRequestTest.java
=> Can't deploy jooby project on Jetty/Tomcat fix #669

md/modules.md
change Config.parseResources to ConfigFactory.parseResources
=> fix module documentation

coverage-report/src/test/java/org/jooby/issues/Issue731.java, jooby-netty/src/main/java/org/jooby/internal/netty/NettyRequest.java
outside a Netty thread (related to #731)
=> A minimal test (failing) to show that a Netty buffer is not accessible

jooby/src/main/java/org/jooby/RequestLogger.java, jooby/src/test/java/org/jooby/RequestLoggerTest.java
=> Add option to log url request including query string

modules/jooby-lang-kotlin/src/main/kotlin/org/jooby/Jooby.kt, modules/jooby-lang-kotlin/src/test/kotlin/examples/kotlin/Fn.kt
#809 
Let me know if you want the rest of the Mutant extension functions to also use reified types.
=> using reified types to extract param, header and body.

modules/jooby-lang-kotlin/src/main/kotlin/org/jooby/Jooby.kt, modules/jooby-lang-kotlin/src/test/kotlin/examples/kotlin/App.kt
#814 
First of all I want to thank you for this amazing framework!
I'm using it with Kotlin and just stumbled upon the need to extend the Kooby class to be able to use it in tests.
=> Makes Kooby Class open

modules/jooby-lang-kotlin/pom.xml, modules/jooby-lang-kotlin/src/main/kotlin/org/jooby/Jooby.kt, modules/jooby-lang-kotlin/src/test/kotlin/examples/kotlin/App.kt, modules/jooby-lang-kotlin/src/test/kotlin/examples/kotlin/Fn.kt, modules/jooby-lang-kotlin/src/test/kotlin/examples/kotlin/KoobyApp.kt
* onStart/onStop callback fix #810
* Kooby as receiver fix #817
=> Kotlin enhancements

jooby/src/main/java/org/jooby/Jooby.java, jooby/src/main/java/org/jooby/Mutant.java, jooby/src/main/java/org/jooby/Parser.java, jooby/src/main/java/org/jooby/Request.java, jooby/src/main/java/org/jooby/internal/BuiltinParser.java, jooby/src/main/java/org/jooby/internal/RequestImpl.java, jooby/src/main/java/org/jooby/internal/mvc/RequestParam.java, jooby/src/main/java/org/jooby/internal/parser/ParserBuilder.java, jooby/src/main/java/org/jooby/internal/parser/ParserExecutor.java, jooby/src/test/java/org/jooby/RequestTest.java, jooby/src/test/java/org/jooby/internal/BuiltinParserTest.java, jooby/src/test/java/org/jooby/internal/RequestImplTest.java, jooby/src/test/java/org/jooby/internal/reqparam/ParserExecutorTest.java, modules/coverage-report/src/test/java/org/jooby/MultipartFormParamFeature.java, modules/coverage-report/src/test/java/org/jooby/ParserDefOrderFeature.java, modules/coverage-report/src/test/java/org/jooby/ParserOrder2Feature.java, modules/coverage-report/src/test/java/org/jooby/ParserOrderFeature.java, modules/coverage-report/src/test/java/org/jooby/UploadHeadersFeature.java, modules/coverage-report/src/test/java/org/jooby/issues/Issue803.java, modules/jooby-spec/src/main/java/org/jooby/internal/spec/RouteParamCollector.java, modules/jooby-spec/src/test/java/apps/ParamTo.java, modules/jooby-spec/src/test/java/org/jooby/spec/RouteParamCollectorTest.java
Optional Upload with malformed file multipart part fix #803
=> favor req.file(name) over req.param(name).toUpload fix #819

pom.xml
For #851 - build passes for me
=> upgrade netty to v.4.1.14.Final

jooby/src/main/java/org/jooby/Jooby.java, jooby/src/main/java/org/jooby/Route.java, jooby/src/main/java/org/jooby/internal/mvc/MvcHandler.java, jooby/src/main/java/org/jooby/internal/mvc/MvcRoutes.java, jooby/src/test/java/org/jooby/internal/mvc/MvcHandlerTest.java
... instead of Method.getDeclaringClass() to avoid abstract class instantiation attempts.
Fixed some compiler warnings in modified classes.
=> 847 - Added implementing class directly to MvcHandler

modules/jooby-bom/pom.xml, pom.xml
=> pac4j-1 upgrade

modules/jooby-bom/pom.xml, pom.xml
=> snake yaml upgrade

modules/jooby-bom/pom.xml, pom.xml
=> upgrade netty 4.21

modules/jooby-bom/pom.xml, pom.xml
=> upgrade jackson

modules/jooby-bom/pom.xml, pom.xml
=> upgrade thymeleaf

modules/jooby-bom/pom.xml, pom.xml
=> upgrade aws

pom.xml
full build passes for me (updated master to HEAD before starting work)
=> querydsl upgrade

pom.xml
=> jcypher upgrade

pom.xml
build passes. coverage run passes
=> bson4jackson upgrade

pom.xml
=> elasticsearch upgrade

pom.xml
=> neo4j.expire upgrade

pom.xml
build from root passes, including the coverage run
=> hazelcast upgrade

doc/available-modules.md, doc/doc/pac4j2/pac4j2.md, modules/jooby-pac4j2/README.md
=> Update pac4j doc

modules/jooby-apitool/src/main/java/org/jooby/internal/apitool/BytecodeRouteParser.java, modules/jooby-apitool/src/test/java/apps/App1056.java, modules/jooby-apitool/src/test/java/org/jooby/apitool/Issue1056.java
=> ApiTool to interpret path params correctly in POSTs without Body annotations

modules/jooby-metrics/src/main/java/org/jooby/metrics/InstrumentedHandler.java, modules/jooby-metrics/src/test/java/org/jooby/metrics/InstrumentedHandlerTest.java
Fixes invalid response status in metrics for deferred methods as reported in #1102
=> Metrics: collect metrics after the response is complete

.gitignore, modules/coverage-report/pom.xml, modules/jooby-apitool/pom.xml, modules/jooby-archetype/pom.xml, modules/jooby-assets-nodejs/pom.xml, modules/jooby-assets-sass/pom.xml, modules/jooby-assets-svg-sprites/pom.xml, modules/jooby-assets/pom.xml, modules/jooby-cassandra/pom.xml, modules/jooby-crash/pom.xml, modules/jooby-frontend/pom.xml, modules/jooby-gradle-plugin/pom.xml, modules/jooby-jdbc/pom.xml, modules/jooby-lang-kotlin/pom.xml, modules/jooby-maven-plugin/pom.xml, modules/jooby-neo4j/pom.xml, modules/jooby-pac4j2/pom.xml, modules/jooby-requery/pom.xml, modules/jooby-whoops/pom.xml, pom.xml
Hi, I just moved all dependency and plugin versions to the project POM for consistency. I also eliminated some duplicates.
=> POM version aggregation

modules/jooby-hazelcast/src/main/java/org/jooby/hazelcast/Hcast.java, modules/jooby-hazelcast/src/main/java/org/jooby/hazelcast/HcastSessionStore.java
(cherry picked from commit 00b084a)
=> cleanup-jooby-hazelcast

pom.xml
Upgraded some maven versions due to security flaws (CVEs) on current versions. Analysis was made with nexus-iq and snyk.
=> Upgrade maven dependencies (next try :-))

modules/jooby-ehcache/src/main/java/org/jooby/ehcache/EhSessionStore.java, modules/jooby-ehcache/src/main/java/org/jooby/internal/ehcache/CacheConfigurationBuilder.java, modules/jooby-ehcache/src/main/java/org/jooby/internal/ehcache/ConfigurationBuilder.java
=> cleanup-jooby-ehcache

modules/jooby-caffeine/src/main/java/org/jooby/caffeine/CaffeineCache.java, modules/jooby-caffeine/src/main/java/org/jooby/caffeine/CaffeineSessionStore.java
=> cleanup-jooby-caffeine

modules/jooby-couchbase/src/main/java/org/jooby/couchbase/AsyncDatastore.java, modules/jooby-couchbase/src/main/java/org/jooby/couchbase/Couchbase.java, modules/jooby-couchbase/src/main/java/org/jooby/couchbase/CouchbaseSessionStore.java, modules/jooby-couchbase/src/main/java/org/jooby/couchbase/Datastore.java, modules/jooby-couchbase/src/main/java/org/jooby/internal/couchbase/AsyncDatastoreImpl.java, modules/jooby-couchbase/src/main/java/org/jooby/internal/couchbase/DatastoreImpl.java, modules/jooby-couchbase/src/main/java/org/jooby/internal/couchbase/IdGenerator.java
=> cleanup-jooby-couchbase

modules/jooby-crash/src/main/java/org/jooby/crash/CrashBootstrap.java, modules/jooby-crash/src/main/java/org/jooby/crash/CrashFSDriver.java, modules/jooby-crash/src/main/java/org/jooby/crash/SimpleProcessContext.java, modules/jooby-crash/src/main/java/org/jooby/crash/WebShellHandler.java
=> cleanup jooby-crash

modules/jooby-flyway/src/main/java/org/jooby/flyway/Flywaydb.java
=> cleanup-jooby-flyway

modules/jooby-filewatcher/src/main/java/org/jooby/filewatcher/FileEventOptions.java, modules/jooby-filewatcher/src/main/java/org/jooby/filewatcher/FileMonitor.java, modules/jooby-filewatcher/src/main/java/org/jooby/filewatcher/FileWatcher.java, modules/jooby-filewatcher/src/main/java/org/jooby/filewatcher/FirstOfPathMatcher.java
=> cleanup-jooby-filewatcher

modules/jooby-hbm/src/main/java/org/jooby/hbm/Hbm.java, modules/jooby-hbm/src/main/java/org/jooby/internal/hbm/RootUnitOfWork.java, modules/jooby-hbm/src/main/java/org/jooby/internal/hbm/ScanEnvImpl.java, modules/jooby-hbm/src/main/java/org/jooby/internal/hbm/SessionProvider.java, modules/jooby-hbm/src/main/java/org/jooby/internal/hbm/UnitOfWorkProvider.java
=> cleanup-jooby-hbm

modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/ChunkedStream.java, modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/LogIoCallback.java, modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowHandler.java, modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowPush.java, modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowRequest.java, modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowResponse.java, modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowServer.java, modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowSse.java, modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowUpload.java, modules/jooby-undertow/src/main/java/org/jooby/internal/undertow/UndertowWebSocket.java
=> cleanup-jooby-undertow

modules/jooby-whoops/src/main/java/org/jooby/whoops/SourceLocator.java, modules/jooby-whoops/src/main/java/org/jooby/whoops/Whoops.java
=> cleanup-jooby-whoops

modules/jooby-gson/src/main/java/org/jooby/json/GsonParser.java, modules/jooby-gson/src/main/java/org/jooby/json/GsonRenderer.java, modules/jooby-gson/src/main/java/org/jooby/json/Gzon.java
=> cleanup-jooby-gson

modules/jooby-spymemcached/src/main/java/org/jooby/internal/memcached/MemcachedClientProvider.java, modules/jooby-spymemcached/src/main/java/org/jooby/memcached/SpySessionStore.java
=> cleanup-jooby-spymemcached

modules/jooby-sitemap/src/main/java/org/jooby/internal/sitemap/JSitemap.java, modules/jooby-sitemap/src/main/java/org/jooby/internal/sitemap/SitemapHandler.java
=> cleanup-jooby-sitemap

modules/jooby-servlet/src/main/java/org/jooby/servlet/ServletServletRequest.java, modules/jooby-servlet/src/main/java/org/jooby/servlet/ServletUpload.java
=> cleanup-jooby-servlet

modules/jooby-scanner/src/main/java/org/jooby/scanner/Scanner.java
=> cleanup-jooby-scanner

modules/jooby-gradle-plugin/src/main/java/org/jooby/run/AssetTask.java, modules/jooby-gradle-plugin/src/main/java/org/jooby/run/JoobyContainer.java, modules/jooby-gradle-plugin/src/main/java/org/jooby/run/JoobyProject.java, modules/jooby-gradle-plugin/src/main/java/org/jooby/run/JoobyTask.java
=> cleanup-jooby-gradle-plugin

modules/jooby-rxjava/src/main/java/org/jooby/rx/ExecSchedulerHook.java, modules/jooby-rxjava/src/main/java/org/jooby/rx/Rx.java
=> cleanup-jooby-rxjava

modules/jooby-quartz/src/main/java/org/jooby/internal/quartz/JobExpander.java, modules/jooby-quartz/src/main/java/org/jooby/internal/quartz/MethodJobDetail.java, modules/jooby-quartz/src/main/java/org/jooby/internal/quartz/QuartzConnectionProvider.java, modules/jooby-quartz/src/main/java/org/jooby/internal/quartz/ReflectiveJob.java, modules/jooby-quartz/src/main/java/org/jooby/quartz/Quartz.java
=> cleanup-jooby-quartz

modules/jooby-hbv/src/main/java/org/jooby/hbv/Hbv.java, modules/jooby-hbv/src/main/java/org/jooby/hbv/HbvConstraintValidatorFactory.java, modules/jooby-hbv/src/main/java/org/jooby/hbv/HbvFactory.java, modules/jooby-hbv/src/main/java/org/jooby/hbv/HbvParser.java
=> cleanup-jooby-hbv

modules/jooby-cassandra/src/main/java/org/jooby/cassandra/Cassandra.java, modules/jooby-cassandra/src/main/java/org/jooby/cassandra/CassandraMapper.java, modules/jooby-cassandra/src/main/java/org/jooby/cassandra/CassandraSessionStore.java, modules/jooby-cassandra/src/main/java/org/jooby/cassandra/ConnectionString.java, modules/jooby-cassandra/src/main/java/org/jooby/cassandra/Datastore.java
=> cleanup-jooby-cassandra

modules/jooby-commons-email/src/main/java/org/jooby/internal/mail/EmailFactory.java, modules/jooby-commons-email/src/main/java/org/jooby/internal/mail/HtmlEmailProvider.java, modules/jooby-commons-email/src/main/java/org/jooby/internal/mail/ImageHtmlEmailProvider.java, modules/jooby-commons-email/src/main/java/org/jooby/internal/mail/MultiPartEmailProvider.java, modules/jooby-commons-email/src/main/java/org/jooby/internal/mail/SimpleEmailProvider.java, modules/jooby-commons-email/src/main/java/org/jooby/mail/CommonsEmail.java
=> cleanup-jooby-commons-email

modules/jooby-mongodb-rx/src/main/java/org/jooby/mongodb/MongoRx.java
=> cleanup-jooby-mongodb-rx

modules/jooby-mongodb/src/main/java/org/jooby/mongodb/MongoSessionStore.java
=> cleanup-jooby-mongodb

modules/jooby-hbs/src/main/java/org/jooby/hbs/Hbs.java, modules/jooby-hbs/src/main/java/org/jooby/internal/hbs/HbsEngine.java, modules/jooby-hbs/src/main/java/org/jooby/internal/hbs/HbsHelpers.java
=> cleanup-jooby-hbs

modules/jooby-assets/src/main/java/org/jooby/assets/AssetCompiler.java, modules/jooby-assets/src/main/java/org/jooby/assets/AssetOptions.java, modules/jooby-assets/src/main/java/org/jooby/assets/Props.java, modules/jooby-assets/src/main/java/org/jooby/assets/Replace.java, modules/jooby-assets/src/main/java/org/jooby/internal/assets/AssetVars.java, modules/jooby-assets/src/main/java/org/jooby/internal/assets/AssetWriter.java, modules/jooby-assets/src/main/java/org/jooby/internal/assets/LiveCompiler.java, modules/jooby-assets/src/main/java/org/jooby/internal/assets/Watcher.java
added swallowing of mkdir() return value
simplified lambdas
simplified if/else
removed unused throws clauses
=> cleanup jooby-assets

modules/jooby-akka/pom.xml, modules/jooby-akka/src/main/java/org/jooby/akka/Akka.java, modules/jooby-akka/src/test/java/org/jooby/akka/AkkaTest.java, pom.xml
=> code cleanup jooby-akka

modules/jooby-bom/bom.groovy, modules/jooby-jade/src/main/java/org/jooby/jade/Engine.java, modules/jooby-jdbi/src/main/java/org/jooby/jdbi/Jdbi.java, modules/jooby-jdbi/src/main/java/org/skife/jdbi/v2/ExpandedStmtRewriter.java, modules/jooby-run/src/main/java/org/jooby/run/Watcher.java
removed redundant type declarations
remove duplicate throws
removed unnecessary semicolons
=> a little more code cleanup

pom.xml
org.jsoup:jsoup ...................................... 1.8.2 -> 1.11.3
=> updated org.jsoup:jsoup

jooby/src/main/java/org/jooby/Jooby.java, jooby/src/main/java/org/jooby/internal/RequestImpl.java, modules/jooby-assets-clean-css/src/test/java/org/jooby/assets/Generator.java, modules/jooby-assets-svg-sprites/src/main/java/org/jooby/assets/SvgSprites.java, modules/jooby-assets/src/main/java/org/jooby/internal/assets/AssetWriter.java, modules/jooby-netty/src/main/java/org/jooby/internal/netty/NettySslContext.java, modules/jooby-pac4j/src/main/java/org/jooby/internal/pac4j/AuthSerializer.java, modules/jooby-pac4j2/src/main/java/org/jooby/internal/pac4j2/Pac4jSessionStore.java, modules/jooby-run/src/main/java/org/jooby/run/Main.java, pom.xml
added taint marker as first step for fixing taints/sinks.
=> Taint analysis

doc/doc/parser-and-renderer/parser-and-renderer.md, doc/doc/yasson/README.md, modules/jooby-yasson/pom.xml, modules/jooby-yasson/src/main/java/org/jooby/json/Yasson.java, modules/jooby-yasson/src/main/java/org/jooby/json/YassonParser.java, modules/jooby-yasson/src/main/java/org/jooby/json/YassonRenderer.java, modules/jooby-yasson/src/test/java/org/jooby/json/YassonParserTest.java, modules/jooby-yasson/src/test/java/org/jooby/json/YassonRendererTest.java, modules/pom.xml, pom.xml
=> add support the Json-b - JSR -367

modules/jooby-yasson/src/main/java/org/jooby/json/Yasson.java
=> fix name Gson to Json-b

modules/jooby-yasson/src/main/java/org/jooby/json/Yasson.java, modules/jooby-yasson/src/main/java/org/jooby/json/YassonRawRenderer.java, modules/jooby-yasson/src/test/java/org/jooby/json/YassonRendererTest.java
=> add support raw jsonb

modules/jooby-bom/pom.xml, modules/jooby-jedis/src/main/java/org/jooby/jedis/Redis.java, modules/jooby-jedis/src/main/java/org/jooby/jedis/RedisProvider.java, modules/jooby-jedis/src/main/java/org/jooby/jedis/RedisSentinel.java, modules/jooby-jedis/src/main/resources/org/jooby/jedis/jedis.conf, modules/jooby-jedis/src/test/java/org/jooby/jedis/RedisSentinelTest.java
=> Redis Sentinel support

modules/jooby-netty/src/main/java/org/jooby/internal/netty/NettyWebSocket.java, modules/jooby-netty/src/test/java/org/jooby/internal/netty/NettyWebSocketTest.java
Based on v1.6.0 b35bc30e494dfde9eb7808be3b647c941129a3d6
=> 1306 fragmented ws frame

doc/doc/hbv/hbv.md
Follow-up to https://gitter.im/jooby-project/jooby?at=5ccaa8a8a4ef09747135de87
=> Add note about import order

modules/jooby-apitool/src/main/java/org/jooby/internal/apitool/TypeJsonDeserializer.java, modules/jooby-apitool/src/test/java/org/jooby/internal/apitool/ComplexMapTypesTest.java
fixes https://github.com/jooby-project/jooby/issues/1329
=> ApiTool map type parsing issue

docs/asciidoc/modules.adoc, docs/asciidoc/modules/pebble.adoc, modules/jooby-bom/pom.xml, modules/jooby-pebble/pom.xml, modules/jooby-pebble/src/main/java/io/jooby/pebble/PebbleModule.java, modules/jooby-pebble/src/main/java/io/jooby/pebble/PebbleTemplateEngine.java, modules/jooby-pebble/src/test/java/io/jooby/pebble/PebbleModuleTest.java, modules/jooby-pebble/src/test/resources/views/index.peb, modules/pom.xml, pom.xml
Added support for Pebble template engine
=> Added support for Pebble template engine

jooby/src/test/java/io/jooby/EnvironmentTest.java, modules/jooby-freemarker/src/test/java/io/jooby/freemarker/FreemarkerModuleTest.java, modules/jooby-handlebars/src/test/java/io/jooby/handlebars/HandlebarsModuleTest.java, tests/src/test/java/io/jooby/FeaturedTest.java
Fixing Path Separators and tackle git ability to checkout windows format (/n/r) and checkin linux (/n)
=> Updated tests in order to properly execute in windows enviroments

modules/jooby-hbm/src/main/java/org/jooby/hbm/Hbm.java, modules/jooby-hbm/src/main/java/org/jooby/internal/hbm/SessionBuilderConfigurer.java, modules/jooby-hbm/src/main/java/org/jooby/internal/hbm/UnitOfWorkProvider.java, modules/jooby-hbm/src/test/java/org/jooby/hbm/HbmTest.java, modules/jooby-hbm/src/test/java/org/jooby/internal/hbm/SessionProviderTest.java, modules/jooby-hbm/src/test/java/org/jooby/internal/hbm/UnitOfWorkProviderTest.java
Supposed to fix #1392 
For cleannes and better testability, I created an explicit interface for the configurer callback. I tried to adapt the test cases also.
=> Ability to use SessionBuilder with jooby-hbm

modules/jooby-hibernate/src/main/java/io/jooby/hibernate/SessionRequest.java, modules/jooby-hibernate/src/main/java/io/jooby/hibernate/TransactionalRequest.java
Note that the TransactionRequest now uses SessionRequest to add the session to the managed context.
ISSUE https://github.com/jooby-project/jooby/issues/1443
=> Add SessionRequest decorator in hibernate module

modules/jooby-apt/src/test/java/io/jooby/apt/MvcModuleCompilerRunner.java
fix needed for build error on windows
=> use System.lineSeparator()

modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/CallbackFilterImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/DevLoginForm.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/LogoutImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/SecurityFilterImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/WebContextImpl.java, modules/jooby-pac4j/src/main/java/io/jooby/pac4j/Pac4jContext.java, modules/jooby-pac4j/src/main/java/io/jooby/pac4j/Pac4jModule.java
Propagated Pac4jOptions in internal classess and use trustProxy in every call to getRequestURL.
Fix for #1571 .
=> fix jooby-pac4j proxy support (bug #1571)

modules/jooby-cli/src/main/resources/cli/pom.xml.hbs
=> Mark conf directory as resource directory

pom.xml
previous had security problem CVE-2020-1757
=> update undertow version to 2.1.0.Final

modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/AnnotationParser.java, modules/jooby-openapi/src/test/java/issues/Issue1768.java, modules/jooby-openapi/src/test/java/issues/i1768/App1768.java, modules/jooby-openapi/src/test/java/issues/i1768/Controller1768.java
=> Added support for OpenAPI operating hiding annotations

modules/jooby-apt/src/main/java/io/jooby/internal/apt/TypeDefinition.java, modules/jooby-apt/src/test/java/source/ArrayRoute.java, modules/jooby-apt/src/test/java/source/Bean.java, modules/jooby-apt/src/test/java/tests/ModuleCompilerTest.java
=> [jooby-apt] Wrong return type generated for array routes

modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/OpenAPIParser.java, modules/jooby-openapi/src/test/java/issues/i1855/App1855.java, modules/jooby-openapi/src/test/java/issues/i1855/Controller1855.java, modules/jooby-openapi/src/test/java/issues/i1855/Issue1855.java
=> [jooby-openapi] Fix for NPE if @Schema is w/o 'implementation'

docs/asciidoc/dev-tools.adoc
=> Fix wrong property name in docs.

docs/asciidoc/context.adoc, docs/asciidoc/mvc-api.adoc, jooby/src/main/java/io/jooby/Context.java, jooby/src/main/java/io/jooby/ParamLookup.java, jooby/src/main/java/io/jooby/ParamSource.java, jooby/src/main/java/io/jooby/annotations/Param.java, jooby/src/main/java/io/jooby/internal/ParamLookupImpl.java, modules/jooby-apt/src/main/java/io/jooby/apt/Annotations.java, modules/jooby-apt/src/main/java/io/jooby/internal/apt/ParamDefinition.java, modules/jooby-apt/src/main/java/io/jooby/internal/apt/ParamKind.java, modules/jooby-apt/src/main/java/io/jooby/internal/apt/asm/ParamLookupWriter.java, modules/jooby-apt/src/test/java/source/ParamSourceCheckerContext.java, modules/jooby-apt/src/test/java/source/RouteWithParamLookup.java, modules/jooby-apt/src/test/java/tests/ModuleCompilerTest.java, modules/jooby-test/src/test/java/io/jooby/LookupTest.java
Closes #1968
~Docs will follow if the API is finalized.~ Added the docs.
=> Parameter lookup feature for script and MVC routes

jooby/src/main/java/io/jooby/FileDownload.java
This is a small enhancement on my previous pull request.
=> Allow creating FileDownload from a byte array

jooby/src/main/java/io/jooby/internal/FormdataNode.java, jooby/src/main/java/io/jooby/internal/UrlParser.java, pom.xml, tests/src/test/java/io/jooby/FeaturedTest.java
=> Fix for double urldecoding with Formdata/Multipart

modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/AnnotationParser.java, modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/RouteParser.java, modules/jooby-openapi/src/test/java/examples/MvcAppWithRoutes.java, modules/jooby-openapi/src/test/java/io/jooby/openapi/OpenAPIGeneratorTest.java, modules/jooby-openapi/src/test/kotlin/kt/KtMvcAppWithRoutes.kt, modules/jooby-openapi/src/test/kotlin/kt/KtMvcInstanceApp.kt, modules/jooby-openapi/src/test/kotlin/kt/KtMvcObjectApp.kt, modules/jooby-openapi/src/test/kotlin/kt/KtObjectController.kt
May close #1987 and may also close #1986
=> OpenAPI generator now supports routes() and Kotlin objects

modules/jooby-openapi/pom.xml, modules/jooby-openapi/src/test/java/issues/i2004/Issue2004.java, modules/jooby-openapi/src/test/kotlin/kt/issues/i2004/App2004.kt, modules/jooby-openapi/src/test/kotlin/kt/issues/i2004/Controller2004.kt
example for #2004 
@imeszaros can you review?
Thanks
=> OpenAPI: document example on Data? class used as arguments

docs/asciidoc/context.adoc, docs/asciidoc/templates.adoc, jooby/src/main/java/io/jooby/Context.java, jooby/src/main/java/io/jooby/Jooby.java, jooby/src/main/java/io/jooby/ModelAndView.java, jooby/src/main/java/io/jooby/Router.java, jooby/src/main/java/io/jooby/internal/LocaleUtils.java, jooby/src/main/java/io/jooby/internal/RouterImpl.java, modules/jooby-freemarker/src/main/java/io/jooby/freemarker/FreemarkerTemplateEngine.java, modules/jooby-freemarker/src/test/java/io/jooby/freemarker/FreemarkerModuleTest.java, modules/jooby-freemarker/src/test/resources/views/locales.ftl, modules/jooby-pebble/src/main/java/io/jooby/pebble/PebbleTemplateEngine.java, modules/jooby-pebble/src/test/java/io/jooby/pebble/PebbleModuleTest.java, modules/jooby-pebble/src/test/resources/messages.properties, modules/jooby-pebble/src/test/resources/messages_de.properties, modules/jooby-pebble/src/test/resources/messages_de_AT.properties, modules/jooby-pebble/src/test/resources/messages_en_GB.properties, modules/jooby-pebble/src/test/resources/views/locales.peb, modules/jooby-thymeleaf/src/main/java/io/jooby/internal/thymeleaf/ThymeleafTemplateEngine.java, tests/src/test/java/io/jooby/FeaturedTest.java, tests/src/test/java/io/jooby/LocaleUtilsTest.java
May close #2006
I need to write test cases and test it more, but what do you think?
I didn't find any way to set the locale for rocker and handlebars.
=> Ability to match request locale and use it for templates

modules/jooby-gradle-plugin/src/main/java/io/jooby/gradle/RunTask.java
- Shutdown hooks are not trigger by Gradle daemon, removed the shutdown hook
- We start a new thread to shutdown on Enter key (this still works), this same threads throws a NoSuchElementException when Gradle disconnect I/O
- We now block this thread either by I/O disconnectd or Enter key and run a shutdown
- Conclusion:
- Ctrl+ C works as expected (normal shutdown)
- IDE integration works as expected (normal shutdown)
- In both cases, daemon can be reused in next run!!!
Fix #1947
=> Gradle: joobyRun now shutdown properly on Ctrl+C

modules/jooby-cli/src/main/java/io/jooby/cli/CreateCmd.java, modules/jooby-cli/src/main/resources/cli/UnitTest.java.hbs, modules/jooby-cli/src/main/resources/cli/UnitTest.kt.hbs
=> CLI: change unit test for MVC apps not to use MockRouter

modules/jooby-utow/src/main/java/io/jooby/utow/Utow.java
=> Fix exception handling at startup time

modules/jooby-kafka/pom.xml, modules/jooby-kafka/src/main/java/io/jooby/kafka/KafkaModule.java, modules/pom.xml
/**
* Creates a new kafka producer module using the <code>kafka.producer</code> property key.
* This key must be present in the application configuration file, like:
*
* <pre>{@code
*  kafka.producer.bootstrap.servers = "localhost:9092"
*  kafka.producer.acks = "all"
*  kafka.producer.retries = 0
*  kafka.producer.key.serializer = "org.apache.kafka.common.serialization.StringSerializer"
*  kafka.producer.value.serializer = "org.apache.kafka.common.serialization.StringSerializer"
* }</pre>
*
* Creates a new kafka consumer module using the <code>kafka.consumer</code> property key.
* This key must be present in the application configuration file, like:
*
* <pre>{@code
*  kafka.consumer.bootstrap.servers = "localhost:9092"
*  kafka.consumer.group.id = "group A"
* …
=> add kafka module to jooby

jooby/src/main/java/io/jooby/Jooby.java, jooby/src/main/java/io/jooby/exception/StartupException.java, tests/src/test/java/io/jooby/Issue2107.java
=> Logging exceptions occurred at app initialization.

docs/asciidoc/routing.adoc, jooby/src/main/java/io/jooby/Jooby.java, jooby/src/main/java/io/jooby/internal/RouterImpl.java, jooby/src/test/kotlin/io/jooby/Idioms.kt, jooby/src/test/kotlin/io/jooby/SubApp.kt, modules/jooby-bom/pom.xml, modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/ReturnTypeParser.java, modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/RouteParser.java, modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/TypeFactory.java, modules/jooby-openapi/src/test/java/issues/i1905/App1905.java, modules/jooby-openapi/src/test/java/issues/i1905/Issue1905.java, modules/jooby-openapi/src/test/java/issues/i1905/SubApp1905.java, modules/jooby-openapi/src/test/kotlin/kt/i1905/App1905.kt, modules/jooby-openapi/src/test/kotlin/kt/i1905/Issue1905.kt, modules/jooby-openapi/src/test/kotlin/kt/i1905/SubApp1905.kt, tests/src/test/java/io/jooby/i1905/A1905.java, tests/src/test/java/io/jooby/i1905/AService1905.java, tests/src/test/java/io/jooby/i1905/B1905.java, tests/src/test/java/io/jooby/i1905/BService1905.java, tests/src/test/java/io/jooby/i1905/Issue1905.java
- Fully load an application
- We need lazy initialization to bind everything properly
- Update documentation
- Update openapi
@imeszaros have special attention to the documentation, want to make it clear we need lazy initialization
Fix #1905 #1835
=> Jooby.install(Supplier<Jooby>)

docs/asciidoc/modules/jasypt.adoc, docs/asciidoc/modules/modules.adoc, jooby/src/main/java/io/jooby/Environment.java, modules/jooby-jasypt/pom.xml, modules/jooby-jasypt/src/main/java/io/jooby/jasypt/JasyptModule.java, modules/jooby-jasypt/src/test/java/io/jooby/jasypt/JasyptModuleTest.java, modules/pom.xml, pom.xml
- Added Environment.setConfig(Config) too
Fixes #2127
=> Add Jasypt module for encrypted properties

modules/jooby-apt/pom.xml, modules/jooby-apt/src/main/java/io/jooby/apt/Annotations.java, modules/jooby-apt/src/test/java/io/jooby/apt/JaxrsTest.java
=> jooby-apt: remove JAXRS dependency

pom.xml
Undertow version upgraded 2.2.2.Final -> 2.2.3.Final
=> Undertow version upgraded 2.2.2.Final -> 2.2.3.Final

docs/src/main/java/io/jooby/adoc/Git.java, jooby/src/main/java/io/jooby/EnvironmentOptions.java, jooby/src/main/java/io/jooby/Jooby.java, jooby/src/main/java/io/jooby/internal/x509/JdkSslContext.java, jooby/src/main/java/io/jooby/internal/x509/SslContext.java, modules/jooby-apt/src/test/java/io/jooby/apt/MvcModuleCompilerRunner.java, modules/jooby-gradle-plugin/src/main/java/io/jooby/gradle/BaseTask.java, modules/jooby-jetty/src/main/java/io/jooby/jetty/Jetty.java, modules/jooby-pac4j/src/main/java/io/jooby/internal/pac4j/WebContextImpl.java, modules/jooby-run/src/main/java/io/jooby/run/JoobyRun.java
replace toArray(new T[size]) with toArray(new T[0]) for better performance
https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion
=> Optimize toArray

modules/jooby-jackson/src/main/java/io/jooby/json/JacksonModule.java
Remove extra else in if-else in Jackson Module
=> jackson optimize if-else

modules/jooby-hibernate/src/main/java/io/jooby/hibernate/HibernateModule.java
HibernateModule - accept list for constructor and scan to avoid copying list to a new array.
=> HibernateModule : Accept list in constructor and scan

modules/jooby-quartz/src/main/java/io/jooby/quartz/QuartzModule.java
Quartz module - accept list in constructor to avoid copying list to a new array.
=> Quartz - Accept list in constructor

modules/jooby-hibernate/src/main/java/io/jooby/hibernate/TransactionalRequest.java
Dropping the dependency on `SessionRequest` allowed to only manage session lifecycle for transactional routes.
Closes #2232
=> TransactionalRequests should only manage sessions for transactional routes

modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyPipeline.java
=> Enable netty ws compression if compressionLevel option is specified

modules/jooby-apt/src/main/java/io/jooby/internal/apt/ParamDefinition.java
=> Allow other NonNull/Nullable annotations for APT

jooby/src/main/java/io/jooby/Environment.java, jooby/src/test/java/io/jooby/EnvironmentTest.java
=> Do not override config origins

modules/jooby-jackson/src/main/java/io/jooby/json/JacksonModule.java
=>  Adds ObjectMapper class registration besides the mapper class.

docs/asciidoc/modules/jstachio.adoc, docs/asciidoc/modules/modules.adoc, modules/jooby-jstachio/pom.xml, modules/jooby-jstachio/src/main/java/io/jooby/jstachio/JStachioHandler.java, modules/jooby-jstachio/src/main/java/io/jooby/jstachio/JStachioMessageEncoder.java, modules/jooby-jstachio/src/main/java/io/jooby/jstachio/JStachioModule.java, modules/jooby-jstachio/src/main/java/io/jooby/jstachio/JStachioResultHandler.java, modules/jooby-jstachio/src/main/java/io/jooby/jstachio/JoobyJStachioConfig.java, modules/jooby-jstachio/src/main/java/module-info.java, modules/pom.xml, pom.xml
Add jstachio support to jooby.
=> JStachio module #2864

docs/asciidoc/modules/avaje-jsonb.adoc, docs/asciidoc/modules/modules.adoc, modules/jooby-avaje-jsonb/pom.xml, modules/jooby-avaje-jsonb/src/main/java/io/jooby/avaje/jsonb/AvajeJsonbModule.java, modules/jooby-avaje-jsonb/src/main/java/module-info.java, modules/jooby-avaje-jsonb/src/test/java/io/jooby/avaje/jsonb/AvajeJsonbModuleTest.java, modules/pom.xml, pom.xml
Hello,
I have added the Avaje JsonB module, Support for JSON encoding and decoding using [Avaje-JsonB](https://github.com/avaje/avaje-jsonb).
Please assist in reviewing at your convenience. Thank you.
=> Creates a new Avaje-JsonB module

pom.xml
Reverts jooby-project/jooby#2940
=> Revert "build(deps): bump jackson-databind from 2.15.0 to 2.15.1"

modules/jooby-cli/src/main/java/io/jooby/cli/CreateCmd.java, modules/jooby-cli/src/main/resources/cli/App.java.hbs
=> fix: server code generation

jooby/src/main/java/io/jooby/Value.java
I checked all implementations to make sure it was NonNull.
=> Value.toMultimap should be NonNull

docs/asciidoc/index.adoc
=> 📖 Cleaned up Introduction docs

modules/jooby-graphql/src/main/java/io/jooby/internal/graphql/GraphQLHandler.java
closes [#3203](https://github.com/jooby-project/jooby/issues/3203)
=> use graphQLContext instead of context

docs/asciidoc/modules/gson.adoc
=> :scroll: Fixed imports of GsonModule in docs

modules/jooby-openapi/pom.xml, modules/jooby-openapi/src/main/java/io/jooby/internal/openapi/AnnotationParser.java, modules/jooby-openapi/src/test/java/issues/i3397/App3397.java, modules/jooby-openapi/src/test/java/issues/i3397/Controller3397.java, modules/jooby-openapi/src/test/java/issues/i3397/Issue3397.java
closes https://github.com/jooby-project/jooby/issues/3397
=> [openapi] Fix parsing avaje bean scope controllers

pom.xml
=> Bump Guice to 6.0.0

modules/jooby-apt/pom.xml, modules/jooby-apt/src/main/java/io/jooby/internal/apt/CodeBlock.java, modules/jooby-apt/src/main/java/io/jooby/internal/apt/escape/AggregateTranslator.java, modules/jooby-apt/src/main/java/io/jooby/internal/apt/escape/CharSequenceTranslator.java, modules/jooby-apt/src/main/java/io/jooby/internal/apt/escape/CodePointTranslator.java, modules/jooby-apt/src/main/java/io/jooby/internal/apt/escape/EscapeUtils.java, modules/jooby-apt/src/main/java/io/jooby/internal/apt/escape/JavaUnicodeEscaper.java, modules/jooby-apt/src/main/java/io/jooby/internal/apt/escape/LookupTranslator.java, modules/jooby-apt/src/main/java/io/jooby/internal/apt/escape/UnicodeEscaper.java
Remove commons-text as a dependency of jooby-apt
=> Add commons-text java escaping #3462

docs/asciidoc/modules/avaje-inject.adoc, modules/jooby-avaje-inject/src/main/java/io/jooby/avaje/inject/AvajeInjectModule.java, modules/jooby-avaje-inject/src/main/java/io/jooby/avaje/inject/JoobyPropertyPlugin.java, pom.xml
=> Bump Avaje Inject to 10.0

docs/asciidoc/testing.adoc, modules/jooby-test/src/main/java/io/jooby/test/JoobyTest.java
Commit 0ef123728fe6447ea15be5145ad5634ef513eee4 changed the random port behavior for methods.
=> Fix port documentation for JoobyTest

docs/asciidoc/index.adoc, docs/asciidoc/problem-details.adoc, jooby/src/main/java/io/jooby/exception/InvalidCsrfToken.java, jooby/src/main/java/io/jooby/exception/MethodNotAllowedException.java, jooby/src/main/java/io/jooby/exception/NotAcceptableException.java, jooby/src/main/java/io/jooby/exception/NotFoundException.java, jooby/src/main/java/io/jooby/exception/StatusCodeException.java, jooby/src/main/java/io/jooby/exception/TypeMismatchException.java, jooby/src/main/java/io/jooby/exception/UnsupportedMediaType.java, jooby/src/main/java/io/jooby/problem/HttpProblemMappable.java, jooby/src/main/java/io/jooby/problem/ProblemDetailsHandler.java
documentation, minor improvements
=> Problem Details documentation

modules/jooby-hibernate/src/main/java/io/jooby/hibernate/HibernateModule.java, modules/jooby-hibernate/src/main/java/io/jooby/hibernate/SessionRequest.java, modules/jooby-hibernate/src/main/java/io/jooby/hibernate/StatelessSessionProvider.java, modules/jooby-hibernate/src/main/java/io/jooby/hibernate/TransactionalRequest.java, modules/jooby-hibernate/src/main/java/io/jooby/internal/hibernate/RequestSessionFactory.java, modules/jooby-hibernate/src/main/java/io/jooby/internal/hibernate/StatelessSessionServiceProvider.java
- Add statless session support to TransactialRequest
```java
{
use(new TransactionalRequest().useStatelessSession);
}
```
fix #3572
=> hibernate: add StatelessSession support

modules/jooby-netty/src/main/java/io/jooby/internal/netty/NettyHandler.java
https://github.com/jooby-project/jooby/issues/3580 catch few more exceptions thrown by the netty decoder
=> Netty handler exception handling

modules/jooby-hibernate/src/main/java/io/jooby/internal/hibernate/RequestSessionFactory.java
=> #3586 Fix RequestSessionFactory.StatefulSessionFactory create returning null session

modules/jooby-avaje-inject/src/main/java/io/jooby/avaje/inject/JoobyPropertyPlugin.java
=> [Avaje Inject Module] Fix property plugin

pom.xml
will solve the last Reproducible Builds issue after #3662 
see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/io/jooby/README.md
=> drop unused property
